eSTARlight: photonNucleusLuminosity Class Reference
photonNucleusLuminosity Class Reference
#include <gammaaluminosity.h>
Public Member Functions
photonNucleusLuminosity (const inputParameters &input, beamBeamSystem &bbsystem)
~photonNucleusLuminosity ()
double slopeParameter () const
returns slope of t-distribution [(GeV/c)^{-2}]
double getChannelMass () const
returns mass of the produced system [GeV/c^2]
double getBNORM () const
beamBeamSystem getbbs () const
returns beamBeamSystem
double vmPhotonCoupling () const
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
double vmQ2Power (double Q2) const
double getDefaultC () const
double maxPhotonEnergy () const
returns max photon energy in lab frame [GeV] (for vectormesons only)
void crossSectionCalculation (const double bwnormsave)
double getcsgA (const double Egamma, const double Q2, const int beam)
double e_getcsgA (const double Egamma, double Q2, const double W, const int beam)
double getcsgA_Q2_dep (const double Q2)
double photonFlux (const double Egamma, const int beam)
double photonFlux (const double Egamma, const double Q2)
double integrated_Q2_dep (const double Egamma, const double _min=0, const double _max=0)
double integrated_x_section (const double Egamma, const double _min=0, const double _max=0)
std::pair< double, double > * Q2arraylimits (double const Egamma)
double g (double const Egamma, double const Q2)
double sigmagp (const double Wgp)
double sigma_A (const double sig_N, const int beam)
double sigma_N (const double Wgp)
double breitWigner (const double W, const double C)
double nepoint (const double Egamma, const double bmin)
double getPhotonNucleusSigma () const
void setPhotonNucleusSigma (double sigma)
Protected Attributes
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _wMax
const double _yMax
double _photonNucleusSigma
int _printDef
int _impulseSelected
int _quantumGlauber
Private Member Functions
void photonNucleusDifferentialLuminosity ()
double * vmsigmapt (double W, double Egamma, double *SIGMAPT, int beam)
void pttablegen ()
Private Attributes
const double _ptBinWidthInterference
const double _interferenceStrength
const double _protonEnergy
const double _beamLorentzGamma
const std::string _baseFileName
const double _maxW
const double _minW
const unsigned int _nmbWBins
const double _maxRapidity
const unsigned int _nmbRapidityBins
const int _productionMode
const int _beamBreakupMode
const bool _interferenceEnabled
const double _maxPtInterference
const int _nmbPtBinsInterference
Detailed Description
Definition at line 43 of file gammaaluminosity.h.
Constructor & Destructor Documentation
photonNucleusLuminosity()
photonNucleusLuminosity::photonNucleusLuminosity (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 52 of file gammaaluminosity.cpp.
References photonNucleusDifferentialLuminosity().
~photonNucleusLuminosity()
photonNucleusLuminosity::~photonNucleusLuminosity ()
Definition at line 77 of file gammaaluminosity.cpp.
Member Function Documentation
breitWigner()
double photonNucleusCrossSection::breitWigner (const double W, const double C) inherited
Definition at line 1089 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_ANORM, photonNucleusCrossSection::_BNORM, photonNucleusCrossSection::_channelMass, photonNucleusCrossSection::_particleType, photonNucleusCrossSection::_width, starlightConstants::FOURPRONG, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::kaonChargedMass, starlightConstants::mel, starlightConstants::muonMass, starlightConstants::OMEGA, starlightConstants::PHI, starlightConstants::pionChargedMass, starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
Referenced by e_wideResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusDifferentialLuminosity().
crossSectionCalculation()
void photonNucleusCrossSection::crossSectionCalculation (const double bwnormsave) inherited
Definition at line 229 of file photonNucleusCrossSection.cpp.
e_getcsgA()
double photonNucleusCrossSection::e_getcsgA (const double Egamma, double Q2, const double W, const int beam) inherited
Definition at line 354 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_bbs, photonNucleusCrossSection::_beamLorentzGamma, photonNucleusCrossSection::_protonEnergy, photonNucleusCrossSection::_vmPhotonCoupling, nucleus::A(), starlightConstants::alpha, beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::formFactor(), starlightConstants::hbarc, starlightConstants::pi, starlightConstants::protonMass, photonNucleusCrossSection::sigma_A(), photonNucleusCrossSection::sigma_N(), and photonNucleusCrossSection::sigmagp().
g()
double photonNucleusCrossSection::g (double const Egamma, double const Q2) inherited
Definition at line 843 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::photonFlux().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::integrated_Q2_dep(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusCrossSection::Q2arraylimits().
getbbs()
beamBeamSystem photonNucleusCrossSection::getbbs () const inline inherited
returns beamBeamSystem
Definition at line 52 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_bbs.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), pttablegen(), and vmsigmapt().
getBNORM()
double photonNucleusCrossSection::getBNORM () const inline inherited
Definition at line 51 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_BNORM.
Referenced by e_wideResonanceCrossSection::crossSectionCalculation(), and wideResonanceCrossSection::crossSectionCalculation().
getChannelMass()
double photonNucleusCrossSection::getChannelMass () const inline inherited
returns mass of the produced system [GeV/c^2]
Definition at line 50 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_channelMass.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::getcsgA_Q2_dep(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), and pttablegen().
getcsgA()
double photonNucleusCrossSection::getcsgA (const double Egamma, const double Q2, const int beam) inherited
Definition at line 237 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_bbs, photonNucleusCrossSection::_beamLorentzGamma, photonNucleusCrossSection::_channelMass, photonNucleusCrossSection::_electronEnergy, photonNucleusCrossSection::_impulseSelected, photonNucleusCrossSection::_maxPhotonEnergy, photonNucleusCrossSection::_targetRadii, photonNucleusCrossSection::_vmPhotonCoupling, nucleus::A(), starlightConstants::alpha, beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::formFactor(), photonNucleusCrossSection::getcsgA_Q2_dep(), starlightConstants::hbarc, starlightConstants::pi, starlightConstants::protonMass, photonNucleusCrossSection::sigma_A(), photonNucleusCrossSection::sigma_N(), and photonNucleusCrossSection::sigmagp().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusDifferentialLuminosity().
getcsgA_Q2_dep()
double photonNucleusCrossSection::getcsgA_Q2_dep (const double Q2) inherited
Definition at line 447 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::getChannelMass(), and photonNucleusCrossSection::vmQ2Power().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::integrated_Q2_dep(), and photonNucleusCrossSection::integrated_x_section().
getDefaultC()
double photonNucleusCrossSection::getDefaultC () const inline inherited
Definition at line 55 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_defaultC.
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusDifferentialLuminosity().
getPhotonNucleusSigma()
double photonNucleusCrossSection::getPhotonNucleusSigma () const inline inherited
Definition at line 88 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_photonNucleusSigma.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), and Gammaawidevm::Gammaawidevm().
integrated_Q2_dep()
double photonNucleusCrossSection::integrated_Q2_dep (const double Egamma, const double _min = 0, const double _max = 0) inherited
Definition at line 729 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_electronEnergy, photonNucleusCrossSection::g(), photonNucleusCrossSection::getcsgA_Q2_dep(), starlightConstants::mel, and photonNucleusCrossSection::photonFlux().
Referenced by photonElectronLuminosity::photonNucleusDifferentialLuminosity().
integrated_x_section()
double photonNucleusCrossSection::integrated_x_section (const double Egamma, const double _min = 0, const double _max = 0) inherited
Definition at line 767 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_electronEnergy, photonNucleusCrossSection::getcsgA_Q2_dep(), and starlightConstants::mel.
maxPhotonEnergy()
double photonNucleusCrossSection::maxPhotonEnergy () const inline inherited
returns max photon energy in lab frame [GeV] (for vectormesons only)
Definition at line 56 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_maxPhotonEnergy.
Referenced by incoherentVMCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), and photonNucleusDifferentialLuminosity().
nepoint()
double photonNucleusCrossSection::nepoint (const double Egamma, const double bmin) inherited
Definition at line 873 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_beamLorentzGamma, starlightConstants::alpha, bessel::dbesk0(), bessel::dbesk1(), starlightConstants::hbarc, and starlightConstants::pi.
Referenced by photonNucleusCrossSection::photonFlux().
photonFlux() [1/2]
double photonNucleusCrossSection::photonFlux (const double Egamma, const int beam) inherited
Definition at line 457 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_bbs, photonNucleusCrossSection::_beamBreakupMode, photonNucleusCrossSection::_beamLorentzGamma, photonNucleusCrossSection::_maxPhotonEnergy, photonNucleusCrossSection::_productionMode, nucleus::A(), starlightConstants::alpha, beamBeamSystem::beam1(), beamBeamSystem::beam2(), bessel::dbesk1(), starlightConstants::hbarc, photonNucleusCrossSection::nepoint(), nucleus::nuclearRadius(), beam::photonDensity(), starlightConstants::PHOTONPOMERONINCOHERENT, starlightConstants::PHOTONPOMERONNARROW, starlightConstants::PHOTONPOMERONWIDE, starlightConstants::pi, beamBeamSystem::probabilityOfBreakup(), and nucleus::Z().
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::g(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusCrossSection::integrated_Q2_dep(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), and photonNucleusDifferentialLuminosity().
photonFlux() [2/2]
double photonNucleusCrossSection::photonFlux (const double Egamma, const double Q2) inherited
Definition at line 852 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_electronEnergy, starlightConstants::alpha, starlightConstants::mel, and starlightConstants::pi.
photonNucleusDifferentialLuminosity()
void photonNucleusLuminosity::photonNucleusDifferentialLuminosity () private
Definition at line 82 of file gammaaluminosity.cpp.
References _baseFileName, _beamBreakupMode, _beamLorentzGamma, _interferenceEnabled, _interferenceStrength, _maxPtInterference, _maxRapidity, _maxW, _minW, _nmbPtBinsInterference, _nmbRapidityBins, _nmbWBins, photonNucleusCrossSection::_nWbins, photonNucleusCrossSection::_nYbins, _productionMode, _protonEnergy, photonNucleusCrossSection::_wMax, photonNucleusCrossSection::_wMin, photonNucleusCrossSection::_yMax, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), photonNucleusCrossSection::breitWigner(), starlightConstants::deuteronSlopePar, photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getcsgA(), photonNucleusCrossSection::getDefaultC(), photonNucleusCrossSection::maxPhotonEnergy(), photonNucleusCrossSection::photonFlux(), starlightConstants::protonMass, pttablegen(), and nucleus::Z().
Referenced by photonNucleusLuminosity().
pttablegen()
void photonNucleusLuminosity::pttablegen () private
Definition at line 222 of file gammaaluminosity.cpp.
References _baseFileName, _beamBreakupMode, _beamLorentzGamma, _interferenceStrength, _nmbPtBinsInterference, photonNucleusCrossSection::_nYbins, _protonEnergy, _ptBinWidthInterference, photonNucleusCrossSection::_yMax, starlightConstants::A2, starlightConstants::alpha, beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::formFactor(), photonNucleusCrossSection::getbbs(), photonNucleusCrossSection::getChannelMass(), starlightConstants::hbarc, nucleus::nuclearRadius(), beam::photonDensity(), starlightConstants::pi, beamBeamSystem::probabilityOfBreakup(), starlightConstants::protonMass, photonNucleusCrossSection::sigma_A(), photonNucleusCrossSection::sigmagp(), photonNucleusCrossSection::slopeParameter(), photonNucleusCrossSection::vmPhotonCoupling(), and vmsigmapt().
Referenced by photonNucleusDifferentialLuminosity().
Q2arraylimits()
pair< double, double > * photonNucleusCrossSection::Q2arraylimits (double const Egamma) inherited
Definition at line 800 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_electronEnergy, photonNucleusCrossSection::_fixedQ2range, photonNucleusCrossSection::_maxQ2, photonNucleusCrossSection::_minQ2, photonNucleusCrossSection::g(), and starlightConstants::mel.
Referenced by photonElectronLuminosity::photonNucleusDifferentialLuminosity().
setPhotonNucleusSigma()
void photonNucleusCrossSection::setPhotonNucleusSigma (double sigma) inline inherited
Definition at line 89 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_photonNucleusSigma.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), and wideResonanceCrossSection::crossSectionCalculation().
sigma_A()
double photonNucleusCrossSection::sigma_A (const double sig_N, const int beam) inherited
Definition at line 976 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_bbs, photonNucleusCrossSection::_quantumGlauber, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), starlightConstants::pi, nucleus::rho0(), and nucleus::thickness().
Referenced by incoherentVMCrossSection::crossSectionCalculation(), photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), and pttablegen().
sigma_N()
double photonNucleusCrossSection::sigma_N (const double Wgp) inherited
Definition at line 1079 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_slopeParameter, photonNucleusCrossSection::_vmPhotonCoupling, starlightConstants::alpha, starlightConstants::hbarc, starlightConstants::pi, and photonNucleusCrossSection::sigmagp().
Referenced by incoherentVMCrossSection::crossSectionCalculation(), photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), and incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity().
sigmagp()
double photonNucleusCrossSection::sigmagp (const double Wgp) inherited
Definition at line 905 of file photonNucleusCrossSection.cpp.
References photonNucleusCrossSection::_channelMass, photonNucleusCrossSection::_particleType, starlightConstants::FOURPRONG, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::OMEGA, starlightConstants::PHI, starlightConstants::protonMass, starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
Referenced by incoherentVMCrossSection::crossSectionCalculation(), photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), pttablegen(), and photonNucleusCrossSection::sigma_N().
slopeParameter()
double photonNucleusCrossSection::slopeParameter () const inline inherited
returns slope of t-distribution [(GeV/c)^{-2}]
Definition at line 49 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_slopeParameter.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), and pttablegen().
vmPhotonCoupling()
double photonNucleusCrossSection::vmPhotonCoupling () const inline inherited
vectormeson-photon coupling constant f_v / 4 pi (cf. Eq. 10 in KN PRC 60 (1999) 014903)
Definition at line 53 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_vmPhotonCoupling.
Referenced by pttablegen().
vmQ2Power()
double photonNucleusCrossSection::vmQ2Power (double Q2) const inline inherited
Definition at line 54 of file photonNucleusCrossSection.h.
References photonNucleusCrossSection::_channelMass, photonNucleusCrossSection::_vmQ2Power_c1, and photonNucleusCrossSection::_vmQ2Power_c2.
Referenced by photonNucleusCrossSection::getcsgA_Q2_dep().
vmsigmapt()
double * photonNucleusLuminosity::vmsigmapt (double W, double Egamma, double * SIGMAPT, int beam) private
Definition at line 437 of file gammaaluminosity.cpp.
References _beamLorentzGamma, _nmbPtBinsInterference, _ptBinWidthInterference, beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::formFactor(), photonNucleusCrossSection::getbbs(), starlightConstants::hbarc, and nucleus::nuclearRadius().
Referenced by pttablegen().
Member Data Documentation
_baseFileName
const std::string photonNucleusLuminosity::_baseFileName private
Definition at line 58 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), and pttablegen().
_beamBreakupMode
const int photonNucleusLuminosity::_beamBreakupMode private
Definition at line 65 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), and pttablegen().
_beamLorentzGamma
const double photonNucleusLuminosity::_beamLorentzGamma private
Definition at line 57 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), pttablegen(), and vmsigmapt().
_impulseSelected
int photonNucleusCrossSection::_impulseSelected protected inherited
Definition at line 104 of file photonNucleusCrossSection.h.
Referenced by photonNucleusCrossSection::getcsgA(), and photonNucleusCrossSection::photonNucleusCrossSection().
_interferenceEnabled
const bool photonNucleusLuminosity::_interferenceEnabled private
Definition at line 66 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_interferenceStrength
const double photonNucleusLuminosity::_interferenceStrength private
Definition at line 55 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), and pttablegen().
_maxPtInterference
const double photonNucleusLuminosity::_maxPtInterference private
Definition at line 67 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_maxRapidity
const double photonNucleusLuminosity::_maxRapidity private
Definition at line 62 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_maxW
const double photonNucleusLuminosity::_maxW private
Definition at line 59 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_minW
const double photonNucleusLuminosity::_minW private
Definition at line 60 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_nmbPtBinsInterference
const int photonNucleusLuminosity::_nmbPtBinsInterference private
Definition at line 68 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), pttablegen(), and vmsigmapt().
_nmbRapidityBins
const unsigned int photonNucleusLuminosity::_nmbRapidityBins private
Definition at line 63 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_nmbWBins
const unsigned int photonNucleusLuminosity::_nmbWBins private
Definition at line 61 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_nWbins
const unsigned int photonNucleusCrossSection::_nWbins protected inherited
Definition at line 92 of file photonNucleusCrossSection.h.
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and photonNucleusDifferentialLuminosity().
_nYbins
const unsigned int photonNucleusCrossSection::_nYbins protected inherited
Definition at line 93 of file photonNucleusCrossSection.h.
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), and pttablegen().
_photonNucleusSigma
double photonNucleusCrossSection::_photonNucleusSigma protected inherited
Definition at line 101 of file photonNucleusCrossSection.h.
Referenced by photonNucleusCrossSection::getPhotonNucleusSigma(), and photonNucleusCrossSection::setPhotonNucleusSigma().
_printDef
int photonNucleusCrossSection::_printDef protected inherited
Definition at line 103 of file photonNucleusCrossSection.h.
_productionMode
const int photonNucleusLuminosity::_productionMode private
Definition at line 64 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity().
_protonEnergy
const double photonNucleusLuminosity::_protonEnergy private
Definition at line 56 of file gammaaluminosity.h.
Referenced by photonNucleusDifferentialLuminosity(), and pttablegen().
_ptBinWidthInterference
const double photonNucleusLuminosity::_ptBinWidthInterference private
Definition at line 54 of file gammaaluminosity.h.
Referenced by pttablegen(), and vmsigmapt().
_quantumGlauber
int photonNucleusCrossSection::_quantumGlauber protected inherited
Definition at line 105 of file photonNucleusCrossSection.h.
Referenced by photonNucleusCrossSection::photonNucleusCrossSection(), and photonNucleusCrossSection::sigma_A().
_wMax
const double photonNucleusCrossSection::_wMax protected inherited
Definition at line 96 of file photonNucleusCrossSection.h.
Referenced by e_wideResonanceCrossSection::e_wideResonanceCrossSection(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusDifferentialLuminosity(), and wideResonanceCrossSection::wideResonanceCrossSection().
_wMin
const double photonNucleusCrossSection::_wMin protected inherited
Definition at line 95 of file photonNucleusCrossSection.h.
Referenced by e_wideResonanceCrossSection::e_wideResonanceCrossSection(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), photonNucleusDifferentialLuminosity(), and wideResonanceCrossSection::wideResonanceCrossSection().
_yMax
const double photonNucleusCrossSection::_yMax protected inherited
Definition at line 97 of file photonNucleusCrossSection.h.
Referenced by incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), pttablegen(), and wideResonanceCrossSection::wideResonanceCrossSection().
The documentation for this class was generated from the following files:
gammaaluminosity.h
gammaaluminosity.cpp