eSTARlight: Gammagammaleptonpair Class Reference
Gammagammaleptonpair Class Reference
#include <gammagammaleptonpair.h>
Public Member Functions
Gammagammaleptonpair (const inputParameters &input, beamBeamSystem &bbsystem)
~Gammagammaleptonpair ()
void twoLeptonCrossSection ()
void calculateTable ()
starlightConstants::event produceEvent (int &ievent)
upcEvent produceEvent ()
eXEvent e_produceEvent ()
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
void read ()
void e_read ()
Static Public Member Functions
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
static double pseudoRapidity (const double px, const double py, const double pz)
calculates pseudorapidity for given 3-momentum
Public Attributes
beamBeamSystem _bbs
randomGenerator _randy
double * _Warray
double * _BWarray
double * _Yarray
double ** _Farray
double ** _Farray1
double ** _Farray2
double ** _f_WYarray
double ** _g_Earray
std::vector< std::pair< double, std::vector< double > > > * _g_EQ2array
double _f_max
double _f_max1
double _f_max2
double _f_WYmax
double _g_Emax
double _g_EQ2max
double _fptarray [500][500]
double _bwnormsave
Protected Attributes
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
const int _ReadInputNPT
const int _ReadInputnumy
const int _ReadInputnumw
const int _ReadInputnumega
const int _ReadInputnumQ2
const int _ReadInputgg_or_gP
const int _ReadInputinterferencemode
const std::string _baseFileName
Private Member Functions
double twoMuonCrossSection (double w)
void pickw (double &w)
void picky (double &y)
void pairMomentum (double w, double y, double &E, double &px, double &py, double &pz)
double pp_1 (double E)
double pp_2 (double E)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
double thetalep (double W, double theta)
void tauDecay (double &px1, double &py1, double &pz1, double &E1, double &px2, double &py2, double &pz2, double &E2)
double getMass ()
double getWidth ()
double getSpin ()
Private Attributes
double _sigmax [starlightLimits::MAXWBINS][starlightLimits::MAXYBINS]
double _sigfint [starlightLimits::MAXWBINS]
double _sigofw [starlightLimits::MAXWBINS]
double _signormw
double _wdelta
double _remainwd
int _ivalwd
double _dgammade [1000]
double _tautolangle [101]
const starlightConstants::particleTypeEnum _GGlepInputpidtest
const int _GGlepInputnumw
const int _GGlepInputnumy
const double _GGlepInputGamma_em
Detailed Description
Definition at line 45 of file gammagammaleptonpair.h.
Constructor & Destructor Documentation
Gammagammaleptonpair()
Gammagammaleptonpair::Gammagammaleptonpair (const inputParameters & input, beamBeamSystem & bbsystem)
Definition at line 52 of file gammagammaleptonpair.cpp.
References eventChannel::_randy, calculateTable(), inputParameters::prodParticleId(), readLuminosity::read(), randomGenerator::Rndom(), starlightConstants::TAUONDECAY, and twoLeptonCrossSection().
~Gammagammaleptonpair()
Gammagammaleptonpair::~Gammagammaleptonpair ()
Definition at line 71 of file gammagammaleptonpair.cpp.
Member Function Documentation
calculateTable()
void Gammagammaleptonpair::calculateTable ()
Definition at line 688 of file gammagammaleptonpair.cpp.
References _dgammade, _tautolangle, starlightConstants::pi, and starlightConstants::tauMass.
Referenced by Gammagammaleptonpair().
e_produceEvent()
eXEvent Gammagammaleptonpair::e_produceEvent () virtual
Implements eventChannel.
Definition at line 858 of file gammagammaleptonpair.cpp.
e_read()
void readLuminosity::e_read () inherited
Definition at line 208 of file readinluminosity.cpp.
References readLuminosity::_baseFileName, readLuminosity::_BWarray, readLuminosity::_bwnormsave, readLuminosity::_f_WYarray, readLuminosity::_f_WYmax, readLuminosity::_g_Earray, readLuminosity::_g_Emax, readLuminosity::_g_EQ2array, readLuminosity::_g_EQ2max, readLuminosity::_ReadInputnumega, readLuminosity::_ReadInputnumQ2, readLuminosity::_ReadInputnumw, readLuminosity::_ReadInputnumy, readLuminosity::_Warray, and readLuminosity::_Yarray.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), and e_Gammaawidevm::e_Gammaawidevm().
getMass()
double Gammagammaleptonpair::getMass () private
Definition at line 819 of file gammagammaleptonpair.cpp.
References _GGlepInputpidtest, starlightConstants::ELECTRON, starlightConstants::mel, starlightConstants::MUON, starlightConstants::muonMass, starlightConstants::tauMass, starlightConstants::TAUON, and starlightConstants::TAUONDECAY.
Referenced by produceEvent(), tauDecay(), thetalep(), twoBodyDecay(), and twoMuonCrossSection().
getSpin()
double Gammagammaleptonpair::getSpin () private
Definition at line 853 of file gammagammaleptonpair.cpp.
Referenced by twoBodyDecay().
getTotalChannelCrossSection()
double eventChannel::getTotalChannelCrossSection () const inline inherited
Definition at line 79 of file eventchannel.h.
References eventChannel::_totalChannelCrossSection.
Referenced by starlight::getTotalCrossSection(), and e_starlight::getTotalCrossSection().
getWidth()
double Gammagammaleptonpair::getWidth () private
Definition at line 844 of file gammagammaleptonpair.cpp.
nmbAccepted()
unsigned long eventChannel::nmbAccepted () const inline inherited
returns number of accepted events
Definition at line 57 of file eventchannel.h.
References eventChannel::_nmbAccepted.
Referenced by starlight::nmbAccepted(), and e_starlight::nmbAccepted().
nmbAttempts()
unsigned long eventChannel::nmbAttempts () const inline inherited
returns number of attempted events
Definition at line 56 of file eventchannel.h.
References eventChannel::_nmbAttempts.
Referenced by starlight::nmbAttempts(), and e_starlight::nmbAttempts().
pairMomentum()
void Gammagammaleptonpair::pairMomentum (double w, double y, double & E, double & px, double & py, double & pz) private
Definition at line 283 of file gammagammaleptonpair.cpp.
References eventChannel::_randy, starlightConstants::pi, pp_1(), pp_2(), and randomGenerator::Rndom().
Referenced by produceEvent().
pickw()
void Gammagammaleptonpair::pickw (double & w) private
Definition at line 170 of file gammagammaleptonpair.cpp.
References _GGlepInputnumw, _ivalwd, eventChannel::_randy, _remainwd, _sigfint, _signormw, _sigofw, readLuminosity::_Warray, _wdelta, and randomGenerator::Rndom().
Referenced by produceEvent().
picky()
void Gammagammaleptonpair::picky (double & y) private
Definition at line 218 of file gammagammaleptonpair.cpp.
References _GGlepInputnumy, _ivalwd, eventChannel::_randy, _remainwd, _sigmax, readLuminosity::_Yarray, starlightLimits::MAXWBINS, starlightLimits::MAXYBINS, and randomGenerator::Rndom().
Referenced by produceEvent().
pp_1()
double Gammagammaleptonpair::pp_1 (double E) private
Definition at line 315 of file gammagammaleptonpair.cpp.
References eventChannel::_bbs, _GGlepInputGamma_em, eventChannel::_randy, beamBeamSystem::beam1(), nucleus::formFactor(), starlightConstants::hbarc, nucleus::nuclearRadius(), starlightConstants::pi, and randomGenerator::Rndom().
Referenced by pairMomentum().
pp_2()
double Gammagammaleptonpair::pp_2 (double E) private
Definition at line 354 of file gammagammaleptonpair.cpp.
References eventChannel::_bbs, _GGlepInputGamma_em, eventChannel::_randy, beamBeamSystem::beam2(), nucleus::formFactor(), starlightConstants::hbarc, nucleus::nuclearRadius(), starlightConstants::pi, and randomGenerator::Rndom().
Referenced by pairMomentum().
produceEvent() [1/2]
starlightConstants::event Gammagammaleptonpair::produceEvent (int & ievent) virtual
Implements eventChannel.
Definition at line 536 of file gammagammaleptonpair.cpp.
References starlightConstants::event::_charge, starlightConstants::event::_fsParticle, starlightConstants::event::_numberOfTracks, eventChannel::_randy, pairMomentum(), pickw(), picky(), starlightConstants::event::px, starlightConstants::event::py, starlightConstants::event::pz, randomGenerator::Rndom(), twoBodyDecay(), and starlightConstants::UNKNOWN.
produceEvent() [2/2]
upcEvent Gammagammaleptonpair::produceEvent () virtual
Implements eventChannel.
Definition at line 599 of file gammagammaleptonpair.cpp.
References eventChannel::_etaCutEnabled, eventChannel::_etaCutMax, eventChannel::_etaCutMin, eventChannel::_nmbAccepted, eventChannel::_nmbAttempts, eventChannel::_ptCutEnabled, eventChannel::_ptCutMax, eventChannel::_ptCutMin, eventChannel::_randy, getMass(), pairMomentum(), pickw(), picky(), eventChannel::pseudoRapidity(), randomGenerator::Rndom(), twoBodyDecay(), and starlightConstants::UNKNOWN.
pseudoRapidity()
double eventChannel::pseudoRapidity (const double px, const double py, const double pz) static inherited
calculates pseudorapidity for given 3-momentum
Definition at line 102 of file eventchannel.cpp.
Referenced by produceEvent().
read()
void readLuminosity::read () inherited
Definition at line 79 of file readinluminosity.cpp.
References readLuminosity::_baseFileName, readLuminosity::_bwnormsave, readLuminosity::_f_max, readLuminosity::_f_max1, readLuminosity::_f_max2, readLuminosity::_Farray, readLuminosity::_Farray1, readLuminosity::_Farray2, readLuminosity::_fptarray, readLuminosity::_ReadInputgg_or_gP, readLuminosity::_ReadInputinterferencemode, readLuminosity::_ReadInputNPT, readLuminosity::_ReadInputnumw, readLuminosity::_ReadInputnumy, readLuminosity::_Warray, readLuminosity::_Yarray, starlightLimits::MAXWBINS, and starlightLimits::MAXYBINS.
Referenced by Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), Gammagammaleptonpair(), and Gammagammasingle::Gammagammasingle().
setTotalChannelCrossSection()
void eventChannel::setTotalChannelCrossSection (double sigma) inline inherited
Definition at line 80 of file eventchannel.h.
References eventChannel::_totalChannelCrossSection.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), Gammagammasingle::singleCrossSection(), and twoLeptonCrossSection().
tauDecay()
void Gammagammaleptonpair::tauDecay (double & px1, double & py1, double & pz1, double & E1, double & px2, double & py2, double & pz2, double & E2) private
Definition at line 725 of file gammagammaleptonpair.cpp.
References _dgammade, eventChannel::_randy, _tautolangle, getMass(), starlightConstants::pi, randomGenerator::Rndom(), and eventChannel::transform().
Referenced by twoBodyDecay().
thetalep()
double Gammagammaleptonpair::thetalep (double W, double theta) private
Definition at line 507 of file gammagammaleptonpair.cpp.
References getMass().
Referenced by twoBodyDecay().
transform()
void eventChannel::transform (const double betax, const double betay, const double betaz, double & E, double & px, double & py, double & pz, int & iFbadevent) static inherited
Lorentz-transforms given 4-vector.
Definition at line 69 of file eventchannel.cpp.
Referenced by tauDecay(), Gammaavectormeson::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), and twoBodyDecay().
twoBodyDecay()
void Gammagammaleptonpair::twoBodyDecay (starlightConstants::particleTypeEnum & ipid, double W, double px0, double py0, double pz0, double & px1, double & py1, double & pz1, double & px2, double & py2, double & pz2, int & iFbadevent) private
Definition at line 396 of file gammagammaleptonpair.cpp.
References _GGlepInputpidtest, eventChannel::_randy, starlightConstants::ELECTRON, getMass(), getSpin(), starlightConstants::MUON, starlightConstants::pi, randomGenerator::Rndom(), tauDecay(), starlightConstants::TAUON, starlightConstants::TAUONDECAY, thetalep(), and eventChannel::transform().
Referenced by produceEvent().
twoLeptonCrossSection()
void Gammagammaleptonpair::twoLeptonCrossSection ()
Definition at line 76 of file gammagammaleptonpair.cpp.
References readLuminosity::_f_max, readLuminosity::_Farray, _GGlepInputnumw, _GGlepInputnumy, readLuminosity::_ReadInputnumw, readLuminosity::_ReadInputnumy, _sigfint, _sigmax, _signormw, _sigofw, readLuminosity::_Warray, readLuminosity::_Yarray, eventChannel::setTotalChannelCrossSection(), and twoMuonCrossSection().
Referenced by Gammagammaleptonpair().
twoMuonCrossSection()
double Gammagammaleptonpair::twoMuonCrossSection (double w) private
Definition at line 151 of file gammagammaleptonpair.cpp.
References starlightConstants::alpha, getMass(), starlightConstants::hbarc, and starlightConstants::pi.
Referenced by twoLeptonCrossSection().
Member Data Documentation
_baseFileName
const std::string readLuminosity::_baseFileName protected inherited
Definition at line 82 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and readLuminosity::read().
_bbs
beamBeamSystem eventChannel::_bbs inherited
Definition at line 73 of file eventchannel.h.
Referenced by starlightDpmJet::init(), starlightPythia::init(), Gammaavectormeson::momenta(), Gammaavectormeson::pickwy(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), pp_1(), pp_2(), starlightPythia::produceEvent(), starlightDpmJet::produceSingleEvent(), and Gammaavectormeson::pTgamma().
_BWarray
double* readLuminosity::_BWarray inherited
Definition at line 52 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and Gammaavectormeson::pickwEgamq2().
_bwnormsave
double readLuminosity::_bwnormsave inherited
Definition at line 72 of file readinluminosity.h.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), readLuminosity::e_read(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), and readLuminosity::read().
_dgammade
double Gammagammaleptonpair::_dgammade[1000] private
Definition at line 66 of file gammagammaleptonpair.h.
Referenced by calculateTable(), and tauDecay().
_etaCutEnabled
bool eventChannel::_etaCutEnabled protected inherited
en/disables cut in eta
Definition at line 90 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_etaCutMax
double eventChannel::_etaCutMax protected inherited
maximum eta, if cut is enabled
Definition at line 92 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_etaCutMin
double eventChannel::_etaCutMin protected inherited
minimum eta, if cut is enabled
Definition at line 91 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_f_max
double readLuminosity::_f_max inherited
Definition at line 62 of file readinluminosity.h.
Referenced by readLuminosity::read(), Gammagammasingle::singleCrossSection(), and twoLeptonCrossSection().
_f_max1
double readLuminosity::_f_max1 inherited
Definition at line 63 of file readinluminosity.h.
Referenced by readLuminosity::read().
_f_max2
double readLuminosity::_f_max2 inherited
Definition at line 64 of file readinluminosity.h.
Referenced by readLuminosity::read().
_f_WYarray
double** readLuminosity::_f_WYarray inherited
Definition at line 58 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammaavectormeson::pickwEgamq2(), and readLuminosity::~readLuminosity().
_f_WYmax
double readLuminosity::_f_WYmax inherited
Definition at line 66 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_Farray
double** readLuminosity::_Farray inherited
Definition at line 54 of file readinluminosity.h.
Referenced by Gammaavectormeson::pickwy(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
_Farray1
double** readLuminosity::_Farray1 inherited
Definition at line 55 of file readinluminosity.h.
Referenced by Gammaavectormeson::pickwy(), readLuminosity::read(), and readLuminosity::~readLuminosity().
_Farray2
double** readLuminosity::_Farray2 inherited
Definition at line 56 of file readinluminosity.h.
Referenced by readLuminosity::read(), and readLuminosity::~readLuminosity().
_fptarray
double readLuminosity::_fptarray[500][500] inherited
Definition at line 70 of file readinluminosity.h.
Referenced by readLuminosity::read(), and Gammaavectormeson::vmpt().
_g_Earray
double** readLuminosity::_g_Earray inherited
Definition at line 59 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and readLuminosity::~readLuminosity().
_g_Emax
double readLuminosity::_g_Emax inherited
Definition at line 67 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_g_EQ2array
std::vector< std::pair<double,std::vector<double> > >* readLuminosity::_g_EQ2array inherited
Definition at line 60 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammaavectormeson::pickwEgamq2(), and readLuminosity::~readLuminosity().
_g_EQ2max
double readLuminosity::_g_EQ2max inherited
Definition at line 68 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_GGlepInputGamma_em
const double Gammagammaleptonpair::_GGlepInputGamma_em private
Definition at line 87 of file gammagammaleptonpair.h.
Referenced by pp_1(), and pp_2().
_GGlepInputnumw
const int Gammagammaleptonpair::_GGlepInputnumw private
Definition at line 85 of file gammagammaleptonpair.h.
Referenced by pickw(), and twoLeptonCrossSection().
_GGlepInputnumy
const int Gammagammaleptonpair::_GGlepInputnumy private
Definition at line 86 of file gammagammaleptonpair.h.
Referenced by picky(), and twoLeptonCrossSection().
_GGlepInputpidtest
const starlightConstants::particleTypeEnum Gammagammaleptonpair::_GGlepInputpidtest private
Definition at line 84 of file gammagammaleptonpair.h.
Referenced by getMass(), and twoBodyDecay().
_ivalwd
int Gammagammaleptonpair::_ivalwd private
Definition at line 65 of file gammagammaleptonpair.h.
Referenced by pickw(), and picky().
_nmbAccepted
unsigned long eventChannel::_nmbAccepted protected inherited
number of accepted events
Definition at line 85 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::nmbAccepted(), produceEvent(), and Gammaavectormeson::produceEvent().
_nmbAttempts
unsigned long eventChannel::_nmbAttempts protected inherited
number of attempted events
Definition at line 84 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::nmbAttempts(), produceEvent(), and Gammaavectormeson::produceEvent().
_ptCutEnabled
bool eventChannel::_ptCutEnabled protected inherited
en/disables cut in pt
Definition at line 87 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_ptCutMax
double eventChannel::_ptCutMax protected inherited
maximum pt, if cut is enabled
Definition at line 89 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_ptCutMin
double eventChannel::_ptCutMin protected inherited
minimum pt, if cut is enabled
Definition at line 88 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), produceEvent(), and Gammaavectormeson::produceEvent().
_randy
randomGenerator eventChannel::_randy inherited
Definition at line 74 of file eventchannel.h.
Referenced by Gammaavectormeson::e_produceEvent(), eventChannel::eventChannel(), Gammaavectormeson::Gammaavectormeson(), Gammagammaleptonpair(), Gammaavectormeson::getTheta(), starlightDpmJet::init(), starlightPythia::init(), Gammaavectormeson::momenta(), pairMomentum(), Gammagammasingle::parentMomentum(), Gammagammasingle::pickw(), pickw(), Gammaavectormeson::pickwEgamq2(), Gammaavectormeson::pickwy(), Gammagammasingle::picky(), picky(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), pp_1(), pp_2(), starlightDpmJet::produceDoubleEvent(), produceEvent(), Gammaavectormeson::produceEvent(), Gammagammasingle::produceEvent(), Gammaavectormeson::pTgamma(), tauDecay(), Gammaavectormeson::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), twoBodyDecay(), and Gammaavectormeson::vmpt().
_ReadInputgg_or_gP
const int readLuminosity::_ReadInputgg_or_gP protected inherited
Definition at line 80 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputinterferencemode
const int readLuminosity::_ReadInputinterferencemode protected inherited
Definition at line 81 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputNPT
const int readLuminosity::_ReadInputNPT protected inherited
Definition at line 75 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputnumega
const int readLuminosity::_ReadInputnumega protected inherited
Definition at line 78 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_ReadInputnumQ2
const int readLuminosity::_ReadInputnumQ2 protected inherited
Definition at line 79 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_ReadInputnumw
const int readLuminosity::_ReadInputnumw protected inherited
Definition at line 77 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), readLuminosity::read(), and twoLeptonCrossSection().
_ReadInputnumy
const int readLuminosity::_ReadInputnumy protected inherited
Definition at line 76 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), readLuminosity::read(), and twoLeptonCrossSection().
_remainwd
double Gammagammaleptonpair::_remainwd private
Definition at line 64 of file gammagammaleptonpair.h.
Referenced by pickw(), and picky().
_sigfint
double Gammagammaleptonpair::_sigfint[starlightLimits::MAXWBINS] private
Definition at line 60 of file gammagammaleptonpair.h.
Referenced by pickw(), and twoLeptonCrossSection().
_sigmax
double Gammagammaleptonpair::_sigmax[starlightLimits::MAXWBINS][starlightLimits::MAXYBINS] private
Definition at line 59 of file gammagammaleptonpair.h.
Referenced by picky(), and twoLeptonCrossSection().
_signormw
double Gammagammaleptonpair::_signormw private
Definition at line 62 of file gammagammaleptonpair.h.
Referenced by pickw(), and twoLeptonCrossSection().
_sigofw
double Gammagammaleptonpair::_sigofw[starlightLimits::MAXWBINS] private
Definition at line 61 of file gammagammaleptonpair.h.
Referenced by pickw(), and twoLeptonCrossSection().
_tautolangle
double Gammagammaleptonpair::_tautolangle[101] private
Definition at line 67 of file gammagammaleptonpair.h.
Referenced by calculateTable(), and tauDecay().
_totalChannelCrossSection
double eventChannel::_totalChannelCrossSection protected inherited
Definition at line 94 of file eventchannel.h.
Referenced by eventChannel::getTotalChannelCrossSection(), and eventChannel::setTotalChannelCrossSection().
_Warray
double* readLuminosity::_Warray inherited
Definition at line 51 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammagammasingle::pickw(), pickw(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
_wdelta
double Gammagammaleptonpair::_wdelta private
Definition at line 63 of file gammagammaleptonpair.h.
Referenced by pickw().
_Yarray
double* readLuminosity::_Yarray inherited
Definition at line 53 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammagammasingle::pickw(), Gammagammasingle::picky(), picky(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
The documentation for this class was generated from the following files:
gammagammaleptonpair.h
gammagammaleptonpair.cpp