eSTARlight: pythiaDecayer Class Reference
pythiaDecayer Class Reference
#include <pythiadecayer.h>
Public Member Functions
pythiaDecayer ()
virtual ~pythiaDecayer ()
void init ()
void addParticle (const starlightParticle &p)
upcEvent execute ()
Private Member Functions
pythiaDecayer (Pythia8::Pythia pythia)
bool operator== (const pythiaDecayer &other) const
Private Attributes
Pythia8::Pythia _pythia
Detailed Description
Definition at line 8 of file pythiadecayer.h.
Constructor & Destructor Documentation
pythiaDecayer() [1/2]
pythiaDecayer::pythiaDecayer ()
Definition at line 8 of file pythiadecayer.cpp.
~pythiaDecayer()
pythiaDecayer::~pythiaDecayer () virtual
Definition at line 11 of file pythiadecayer.cpp.
pythiaDecayer() [2/2]
pythiaDecayer::pythiaDecayer (Pythia8::Pythia pythia) private
Member Function Documentation
addParticle()
void pythiaDecayer::addParticle (const starlightParticle & p)
Definition at line 22 of file pythiadecayer.cpp.
References _pythia, lorentzVector::GetE(), starlightParticle::getPdgCode(), lorentzVector::GetPx(), lorentzVector::GetPy(), lorentzVector::GetPz(), and lorentzVector::M().
execute()
upcEvent pythiaDecayer::execute ()
Definition at line 35 of file pythiadecayer.cpp.
References _pythia, upcEvent::addParticle(), and printWarn.
init()
void pythiaDecayer::init ()
Definition at line 13 of file pythiadecayer.cpp.
References _pythia.
operator==()
bool pythiaDecayer::operator== (const pythiaDecayer & other) const private
Member Data Documentation
_pythia
Pythia8::Pythia pythiaDecayer::_pythia private
Definition at line 33 of file pythiadecayer.h.
Referenced by addParticle(), execute(), and init().
The documentation for this class was generated from the following files:
pythiadecayer.h
pythiadecayer.cpp