eSTARlight: starlightParticle Class Reference
starlightParticle Class Reference
#include <starlightparticle.h>
Public Member Functions
starlightParticle ()
starlightParticle (double px, double py, double pz, double e, double mass, int pdgCode, short charge, double vx=0., double vy=0, double vz=0, double vt=0, int firstParent=0, int lastParent=0, int firstDaughter=0, int lastDaughter=0, int status=0)
virtual ~starlightParticle ()
void setPdgCode (int pdgCode)
int getPdgCode () const
void setCharge (short charge)
short getCharge () const
void setMass (short mass)
short getMass () const
void setFirstParent (int parent)
void setLastParent (int parent)
int getFirstParent () const
int getLastParent () const
void setFirstDaughter (int first)
int getFirstDaughter () const
void setLastDaughter (int first)
int getLastDaughter () const
void setStatus (int status)
int getStatus () const
void setVertex (lorentzVector v)
lorentzVector getVertex () const
void SetXYZT (double x, double y, double z, double t)
void SetPxPyPzE (double px, double py, double pz, double e)
double GetPx () const
double GetPy () const
double GetPz () const
double GetE () const
lorentzVector & operator+= (const lorentzVector &vec)
lorentzVector & operator-= (const lorentzVector &vec)
double M2 () const
double M () const
vector3 BoostVector () const
void Boost (const vector3 &beta)
Private Attributes
lorentzVector _vertex
int _pdgCode
short _charge
double _mass
int _firstParent
int _lastParent
int _firstDaughter
int _lastDaughter
int _status
Detailed Description
Definition at line 41 of file starlightparticle.h.
Constructor & Destructor Documentation
starlightParticle() [1/2]
starlightParticle::starlightParticle ()
Definition at line 37 of file starlightparticle.cpp.
starlightParticle() [2/2]
starlightParticle::starlightParticle (double px, double py, double pz, double e, double mass, int pdgCode, short charge, double vx = 0., double vy = 0, double vz = 0, double vt = 0, int firstParent = 0, int lastParent = 0, int firstDaughter = 0, int lastDaughter = 0, int status = 0)
Definition at line 51 of file starlightparticle.cpp.
~starlightParticle()
starlightParticle::~starlightParticle () virtual
Definition at line 67 of file starlightparticle.cpp.
Member Function Documentation
Boost()
void lorentzVector::Boost (const vector3 & beta) inline inherited
Definition at line 81 of file lorentzvector.h.
References lorentzVector::fSpaceVec, lorentzVector::fTime, vector3::Mag2(), lorentzVector::SetXYZT(), vector3::X(), vector3::Y(), and vector3::Z().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics(), starlightPythia::produceEvent(), and starlightDpmJet::produceSingleEvent().
BoostVector()
vector3 lorentzVector::BoostVector () const inline inherited
Definition at line 79 of file lorentzvector.h.
References lorentzVector::fSpaceVec, lorentzVector::fTime, vector3::X(), vector3::Y(), and vector3::Z().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics().
getCharge()
short starlightParticle::getCharge () const inline
Definition at line 55 of file starlightparticle.h.
References _charge.
GetE()
double lorentzVector::GetE () const inline inherited
Definition at line 57 of file lorentzvector.h.
References lorentzVector::fTime.
Referenced by pythiaDecayer::addParticle(), and eventFileWriter::writeEvent().
getFirstDaughter()
int starlightParticle::getFirstDaughter () const inline
Definition at line 66 of file starlightparticle.h.
References _firstDaughter.
getFirstParent()
int starlightParticle::getFirstParent () const inline
Definition at line 62 of file starlightparticle.h.
References _firstParent.
getLastDaughter()
int starlightParticle::getLastDaughter () const inline
Definition at line 69 of file starlightparticle.h.
References _lastDaughter.
getLastParent()
int starlightParticle::getLastParent () const inline
Definition at line 63 of file starlightparticle.h.
References _lastParent.
getMass()
short starlightParticle::getMass () const inline
Definition at line 58 of file starlightparticle.h.
References _mass.
getPdgCode()
int starlightParticle::getPdgCode () const inline
Definition at line 52 of file starlightparticle.h.
References _pdgCode.
Referenced by pythiaDecayer::addParticle().
GetPx()
double lorentzVector::GetPx () const inline inherited
Definition at line 54 of file lorentzvector.h.
References lorentzVector::fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), and eventFileWriter::writeEvent().
GetPy()
double lorentzVector::GetPy () const inline inherited
Definition at line 55 of file lorentzvector.h.
References lorentzVector::fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), and eventFileWriter::writeEvent().
GetPz()
double lorentzVector::GetPz () const inline inherited
Definition at line 56 of file lorentzvector.h.
References lorentzVector::fSpaceVec, and vector3::GetVector().
Referenced by pythiaDecayer::addParticle(), and eventFileWriter::writeEvent().
getStatus()
int starlightParticle::getStatus () const inline
Definition at line 72 of file starlightparticle.h.
References _status.
getVertex()
lorentzVector starlightParticle::getVertex () const inline
Definition at line 75 of file starlightparticle.h.
References _vertex.
M()
double lorentzVector::M () const inline inherited
Definition at line 73 of file lorentzvector.h.
References lorentzVector::M2().
Referenced by pythiaDecayer::addParticle(), nBodyPhaseSpaceGen::generateDecay(), and nBodyPhaseSpaceGen::generateDecayAccepted().
M2()
double lorentzVector::M2 () const inline inherited
Definition at line 72 of file lorentzvector.h.
References lorentzVector::fSpaceVec, lorentzVector::fTime, and vector3::Mag2().
Referenced by lorentzVector::M().
operator+=()
lorentzVector& lorentzVector::operator+= (const lorentzVector & vec) inline inherited
Definition at line 59 of file lorentzvector.h.
References lorentzVector::fSpaceVec, and lorentzVector::fTime.
operator-=()
lorentzVector& lorentzVector::operator-= (const lorentzVector & vec) inline inherited
Definition at line 65 of file lorentzvector.h.
References lorentzVector::fSpaceVec, and lorentzVector::fTime.
setCharge()
void starlightParticle::setCharge (short charge) inline
Definition at line 54 of file starlightparticle.h.
References _charge.
setFirstDaughter()
void starlightParticle::setFirstDaughter (int first) inline
Definition at line 65 of file starlightparticle.h.
References _firstDaughter.
Referenced by starlightPythia::produceEvent().
setFirstParent()
void starlightParticle::setFirstParent (int parent) inline
Definition at line 60 of file starlightparticle.h.
References _firstParent.
setLastDaughter()
void starlightParticle::setLastDaughter (int first) inline
Definition at line 68 of file starlightparticle.h.
References _lastDaughter.
Referenced by starlightPythia::produceEvent().
setLastParent()
void starlightParticle::setLastParent (int parent) inline
Definition at line 61 of file starlightparticle.h.
References _lastParent.
setMass()
void starlightParticle::setMass (short mass) inline
Definition at line 57 of file starlightparticle.h.
References _mass.
setPdgCode()
void starlightParticle::setPdgCode (int pdgCode) inline
Definition at line 51 of file starlightparticle.h.
References _pdgCode.
SetPxPyPzE()
void lorentzVector::SetPxPyPzE (double px, double py, double pz, double e) inline inherited
Definition at line 52 of file lorentzvector.h.
References lorentzVector::SetXYZT().
Referenced by nBodyPhaseSpaceGen::calcEventKinematics().
setStatus()
void starlightParticle::setStatus (int status) inline
Definition at line 71 of file starlightparticle.h.
References _status.
Referenced by starlightPythia::produceEvent().
setVertex()
void starlightParticle::setVertex (lorentzVector v) inline
Definition at line 74 of file starlightparticle.h.
References _vertex.
SetXYZT()
void lorentzVector::SetXYZT (double x, double y, double z, double t) inherited
Definition at line 53 of file lorentzvector.cpp.
References lorentzVector::fSpaceVec, lorentzVector::fTime, and vector3::SetVector().
Referenced by lorentzVector::Boost(), and lorentzVector::SetPxPyPzE().
Member Data Documentation
_charge
short starlightParticle::_charge private
Definition at line 82 of file starlightparticle.h.
Referenced by getCharge(), and setCharge().
_firstDaughter
int starlightParticle::_firstDaughter private
Definition at line 87 of file starlightparticle.h.
Referenced by getFirstDaughter(), and setFirstDaughter().
_firstParent
int starlightParticle::_firstParent private
Definition at line 85 of file starlightparticle.h.
Referenced by getFirstParent(), and setFirstParent().
_lastDaughter
int starlightParticle::_lastDaughter private
Definition at line 88 of file starlightparticle.h.
Referenced by getLastDaughter(), and setLastDaughter().
_lastParent
int starlightParticle::_lastParent private
Definition at line 86 of file starlightparticle.h.
Referenced by getLastParent(), and setLastParent().
_mass
double starlightParticle::_mass private
Definition at line 83 of file starlightparticle.h.
Referenced by getMass(), and setMass().
_pdgCode
int starlightParticle::_pdgCode private
Definition at line 81 of file starlightparticle.h.
Referenced by getPdgCode(), and setPdgCode().
_status
int starlightParticle::_status private
Definition at line 90 of file starlightparticle.h.
Referenced by getStatus(), and setStatus().
_vertex
lorentzVector starlightParticle::_vertex private
Definition at line 79 of file starlightparticle.h.
Referenced by getVertex(), and setVertex().
The documentation for this class was generated from the following files:
starlightparticle.h
starlightparticle.cpp