eSTARlight: e_main.cpp File Reference
e_main.cpp File Reference
#include <iostream>
#include <cstdlib>
#include "reportingUtils.h"
#include "e_starlight.h"
#include "eventfilewriter.h"
#include "e_starlightStandalone.h"
Functions
int main (int, const char **)
Function Documentation
main()
int main (int , const char **)
Definition at line 44 of file e_main.cpp.
References e_starlightStandalone::init(), printCompilerInfo(), printSvnVersion(), and e_starlightStandalone::run().