eSTARlight: vector3 Class Reference
vector3 Class Reference
#include <vector3.h>
Public Member Functions
vector3 ()
vector3 (double *vec)
vector3 (double x, double y, double z)
virtual ~vector3 ()
const double * GetVector () const
void SetVector (double x, double y, double z)
void SetVector (double *vec)
vector3 & operator= (const vector3 &vec)
vector3 & operator+= (const vector3 &vec)
vector3 & operator-= (const vector3 &vec)
double X () const
double Y () const
double Z () const
double Mag2 () const
double Mag () const
Private Attributes
double _vec [3]
Friends
std::ostream & operator<< (std::ostream &out, const vector3 &vec)
Detailed Description
Definition at line 42 of file vector3.h.
Constructor & Destructor Documentation
vector3() [1/3]
vector3::vector3 ()
Definition at line 37 of file vector3.cpp.
References _vec.
vector3() [2/3]
vector3::vector3 (double * vec)
vector3() [3/3]
vector3::vector3 (double x, double y, double z)
Definition at line 45 of file vector3.cpp.
References _vec.
~vector3()
vector3::~vector3 () virtual
Definition at line 53 of file vector3.cpp.
Member Function Documentation
GetVector()
const double* vector3::GetVector () const inline
Definition at line 50 of file vector3.h.
References _vec.
Referenced by lorentzVector::GetPx(), lorentzVector::GetPy(), and lorentzVector::GetPz().
Mag()
double vector3::Mag () const inline
Definition at line 81 of file vector3.h.
References Mag2().
Mag2()
double vector3::Mag2 () const inline
Definition at line 80 of file vector3.h.
References _vec.
Referenced by lorentzVector::Boost(), lorentzVector::M2(), and Mag().
operator+=()
vector3& vector3::operator+= (const vector3 & vec) inline
Definition at line 63 of file vector3.h.
References _vec.
operator-=()
vector3& vector3::operator-= (const vector3 & vec) inline
Definition at line 69 of file vector3.h.
References _vec.
operator=()
vector3& vector3::operator= (const vector3 & vec) inline
Definition at line 55 of file vector3.h.
References _vec.
SetVector() [1/2]
void vector3::SetVector (double x, double y, double z)
Definition at line 57 of file vector3.cpp.
References _vec.
Referenced by lorentzVector::SetXYZT().
SetVector() [2/2]
void vector3::SetVector (double * vec)
Definition at line 65 of file vector3.cpp.
References _vec.
X()
double vector3::X () const inline
Definition at line 76 of file vector3.h.
References _vec.
Referenced by lorentzVector::Boost(), and lorentzVector::BoostVector().
Y()
double vector3::Y () const inline
Definition at line 77 of file vector3.h.
References _vec.
Referenced by lorentzVector::Boost(), and lorentzVector::BoostVector().
Z()
double vector3::Z () const inline
Definition at line 78 of file vector3.h.
References _vec.
Referenced by lorentzVector::Boost(), and lorentzVector::BoostVector().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const vector3 & vec) friend
Definition at line 83 of file vector3.h.
Member Data Documentation
_vec
double vector3::_vec[3] private
Definition at line 92 of file vector3.h.
Referenced by GetVector(), Mag2(), operator+=(), operator-=(), operator=(), SetVector(), vector3(), X(), Y(), and Z().
The documentation for this class was generated from the following files:
vector3.h
vector3.cpp