eSTARlight: spectrumProtonNucleus Class Reference
spectrumProtonNucleus Class Reference
#include <spectrumprotonnucleus.h>
Public Member Functions
spectrumProtonNucleus (const randomGenerator &randy, beamBeamSystem *bb)
virtual double getNucleonNucleonSigma () const
int generateKsingle ()
int generateKdouble ()
double drawKsingle ()
void drawKdouble (float &egamma1, float &egamma2)
void setBeamBeamSystem (beamBeamSystem *bbs)
void setMinGammaEnergy (double energy)
void setMaxGammaEnergy (double energy)
void setBmin (double bmin)
void setBmax (double bmax)
Protected Member Functions
virtual bool generateBreakupProbabilities ()
virtual double getSigma (double) const
virtual double getTransformedNofe (double egamma, double b)
Protected Attributes
double _bMin
double _bMax
int _nBbins
std::vector< double > _probOfBreakup
beamBeamSystem * _beamBeamSystem
Detailed Description
Definition at line 28 of file spectrumprotonnucleus.h.
Constructor & Destructor Documentation
spectrumProtonNucleus()
spectrumProtonNucleus::spectrumProtonNucleus (const randomGenerator & randy, beamBeamSystem * bb)
Definition at line 26 of file spectrumprotonnucleus.cpp.
References spectrum::_bMin.
Member Function Documentation
drawKdouble()
void spectrum::drawKdouble (float & egamma1, float & egamma2) inherited
Get the energy of a single gamma
Parameters
egamma1 variable passed by reference to get the energy of the frst gamma
egamma2 variable passed by reference to get the energy of the second gamma
Returns
energy of the gamma
Definition at line 265 of file spectrum.cpp.
References spectrum::_eGamma, spectrum::_fnDouble, spectrum::_fnDoubleIntCumulative, spectrum::_nK, spectrum::_randy, and randomGenerator::Rndom().
Referenced by starlightDpmJet::produceDoubleEvent().
drawKsingle()
double spectrum::drawKsingle () inherited
Get the energy of a single gamma
Returns
energy of the gamma
Definition at line 226 of file spectrum.cpp.
References spectrum::_eGamma, spectrum::_fnSingleCumulative, spectrum::_nK, spectrum::_randy, and randomGenerator::Rndom().
Referenced by starlightDpmJet::produceEvent(), and starlightPythia::produceEvent().
generateBreakupProbabilities()
bool spectrumProtonNucleus::generateBreakupProbabilities () protected virtual
Generate the hadron breakup probability table
Reimplemented from spectrum.
Definition at line 31 of file spectrumprotonnucleus.cpp.
References spectrum::_beamBeamSystem, spectrum::_bMax, spectrum::_bMin, spectrum::_nBbins, spectrum::_probOfBreakup, beamBeamSystem::beam1(), beamBeamSystem::beam2(), getNucleonNucleonSigma(), nucleus::thickness(), and nucleus::Z().
generateKdouble()
int spectrum::generateKdouble () inherited
Generate a 2-D table of photon energy probabilities Use NK+1 x NK+1 logarithmic steps between Et_min and Eg_max
Definition at line 128 of file spectrum.cpp.
References spectrum::_bMax, spectrum::_bMin, spectrum::_eGamma, spectrum::_eGammaMax, spectrum::_eGammaMin, spectrum::_fnDouble, spectrum::_fnDoubleCumulative, spectrum::_fnDoubleInt, spectrum::_fnDoubleIntCumulative, spectrum::_hadBreakProbCalculated, spectrum::_nBbins, spectrum::_nK, spectrum::_probOfBreakup, spectrum::generateBreakupProbabilities(), spectrum::getSigma(), spectrum::getTransformedNofe(), and starlightConstants::pi.
Referenced by starlightDpmJet::init(), and starlightPythia::init().
generateKsingle()
int spectrum::generateKsingle () inherited
Generate a table of photon energy probabilities Use NK+1 logarithmic steps between Et_min and Eg_max
Definition at line 52 of file spectrum.cpp.
References spectrum::_bMax, spectrum::_bMin, spectrum::_eGamma, spectrum::_eGammaMax, spectrum::_eGammaMin, spectrum::_fnSingle, spectrum::_fnSingleCumulative, spectrum::_hadBreakProbCalculated, spectrum::_nBbins, spectrum::_nK, spectrum::_probOfBreakup, spectrum::generateBreakupProbabilities(), spectrum::getSigma(), spectrum::getTransformedNofe(), and starlightConstants::pi.
Referenced by starlightDpmJet::init(), and starlightPythia::init().
getNucleonNucleonSigma()
virtual double spectrumProtonNucleus::getNucleonNucleonSigma () const inline virtual
Definition at line 32 of file spectrumprotonnucleus.h.
Referenced by generateBreakupProbabilities().
getSigma()
double spectrumProtonNucleus::getSigma (double) const protected virtual
Needs some explanation
Reimplemented from spectrum.
Definition at line 55 of file spectrumprotonnucleus.cpp.
getTransformedNofe()
double spectrum::getTransformedNofe (double egamma, double b) protected virtual inherited
Definition at line 455 of file spectrum.cpp.
References spectrum::_beamBeamSystem, beamBeamSystem::beam1(), beamBeamSystem::beamLorentzGamma(), and beam::photonDensity().
Referenced by spectrum::generateKdouble(), and spectrum::generateKsingle().
setBeamBeamSystem()
void spectrum::setBeamBeamSystem (beamBeamSystem * bbs) inline inherited
Set the beam beam system
Definition at line 63 of file spectrum.h.
References spectrum::_beamBeamSystem.
setBmax()
void spectrum::setBmax (double bmax) inline inherited
Set maximum impact parameter
Definition at line 77 of file spectrum.h.
References spectrum::_bMax.
setBmin()
void spectrum::setBmin (double bmin) inline inherited
Set minimum impact parameter
Definition at line 74 of file spectrum.h.
References spectrum::_bMin.
setMaxGammaEnergy()
void spectrum::setMaxGammaEnergy (double energy) inline inherited
Set the maximum gamma energy
Definition at line 71 of file spectrum.h.
References spectrum::_eGammaMax.
Referenced by starlightDpmJet::init(), and starlightPythia::init().
setMinGammaEnergy()
void spectrum::setMinGammaEnergy (double energy) inline inherited
Set the minimum gamma energy
Definition at line 68 of file spectrum.h.
References spectrum::_eGammaMin.
Referenced by starlightDpmJet::init(), and starlightPythia::init().
Member Data Documentation
_beamBeamSystem
beamBeamSystem* spectrum::_beamBeamSystem protected inherited
Beam beam system
Definition at line 104 of file spectrum.h.
Referenced by generateBreakupProbabilities(), spectrum::generateBreakupProbabilities(), spectrum::getTransformedNofe(), and spectrum::setBeamBeamSystem().
_bMax
double spectrum::_bMax protected inherited
Maximum impact parameter
Definition at line 95 of file spectrum.h.
Referenced by generateBreakupProbabilities(), spectrum::generateBreakupProbabilities(), spectrum::generateKdouble(), spectrum::generateKsingle(), and spectrum::setBmax().
_bMin
double spectrum::_bMin protected inherited
Minimum impact parameter
Definition at line 92 of file spectrum.h.
Referenced by generateBreakupProbabilities(), spectrum::generateBreakupProbabilities(), spectrum::generateKdouble(), spectrum::generateKsingle(), spectrum::setBmin(), and spectrumProtonNucleus().
_nBbins
int spectrum::_nBbins protected inherited
Number of bins in impact parameter
Definition at line 98 of file spectrum.h.
Referenced by generateBreakupProbabilities(), spectrum::generateBreakupProbabilities(), spectrum::generateKdouble(), spectrum::generateKsingle(), and spectrum::spectrum().
_probOfBreakup
std::vector<double> spectrum::_probOfBreakup protected inherited
Vector containing the probability of breakup
Definition at line 101 of file spectrum.h.
Referenced by generateBreakupProbabilities(), spectrum::generateBreakupProbabilities(), spectrum::generateKdouble(), spectrum::generateKsingle(), and spectrum::spectrum().
The documentation for this class was generated from the following files:
spectrumprotonnucleus.h
spectrumprotonnucleus.cpp