eSTARlight: starlightStandalone Class Reference
starlightStandalone Class Reference
#include <starlightStandalone.h>
Public Member Functions
starlightStandalone ()
~starlightStandalone ()
bool init ()
reads configuration file and initializes startlight
bool run ()
creates output file and runs starlight
const std::string & baseFileName () const
const std::string & configFileName () const
returns path to config file
const std::string & eventDataFileName () const
returns path to output file
void setBaseFileName (const std::string &baseFileName)
sets path to base file
void setConfigFileName (const std::string &configFileName)
sets path to config file
void setEventDataFileName (const std::string &eventDataFileName)
sets path to output file
void boostEvent (upcEvent &e)
Boost event from beam CMS to lab system.
Private Attributes
std::string _baseFileName
path to base filename
std::string _configFileName
path to configuration file
std::string _eventDataFileName
path to output file
starlight * _starlight
pointer to starlight instance
inputParameters * _inputParameters
pointer to parameter instance
unsigned int _nmbEventsTot
total number of events to generate (taken from configuration file)
unsigned int _nmbEventsPerFile
maximum number of events written to a single file (not yet implemented)
Detailed Description
Definition at line 46 of file starlightStandalone.h.
Constructor & Destructor Documentation
starlightStandalone()
starlightStandalone::starlightStandalone ()
Definition at line 46 of file starlightStandalone.cpp.
~starlightStandalone()
starlightStandalone::~starlightStandalone ()
Definition at line 54 of file starlightStandalone.cpp.
Member Function Documentation
baseFileName()
const std::string& starlightStandalone::baseFileName () const inline
Definition at line 56 of file starlightStandalone.h.
References _baseFileName.
Referenced by setBaseFileName().
boostEvent()
void starlightStandalone::boostEvent (upcEvent & e)
Boost event from beam CMS to lab system.
Definition at line 163 of file starlightStandalone.cpp.
References _inputParameters, inputParameters::beam1LorentzGamma(), and inputParameters::beam2LorentzGamma().
Referenced by run().
configFileName()
const std::string& starlightStandalone::configFileName () const inline
returns path to config file
Definition at line 57 of file starlightStandalone.h.
References _configFileName.
Referenced by setConfigFileName().
eventDataFileName()
const std::string& starlightStandalone::eventDataFileName () const inline
returns path to output file
Definition at line 58 of file starlightStandalone.h.
References _eventDataFileName.
Referenced by setEventDataFileName().
init()
bool starlightStandalone::init ()
reads configuration file and initializes startlight
Definition at line 59 of file starlightStandalone.cpp.
References _baseFileName, _configFileName, _inputParameters, _nmbEventsPerFile, _nmbEventsTot, _starlight, inputParameters::baseFileName(), inputParameters::configureFromFile(), starlight::init(), inputParameters::init(), inputParameters::nmbEvents(), printWarn, and starlight::setInputParameters().
Referenced by main().
run()
bool starlightStandalone::run ()
creates output file and runs starlight
Definition at line 111 of file starlightStandalone.cpp.
References _baseFileName, _eventDataFileName, _inputParameters, _nmbEventsPerFile, _nmbEventsTot, _starlight, inputParameters::baseFileName(), boostEvent(), fileWriter::close(), starlight::getTotalCrossSection(), inputParameters::inputBranchingRatio(), starlight::nmbAccepted(), starlight::nmbAttempts(), fileWriter::open(), printInfo, printWarn, starlight::produceEvent(), progressIndicator(), and inputParameters::pythiaFullEventRecord().
Referenced by main().
setBaseFileName()
void starlightStandalone::setBaseFileName (const std::string & baseFileName) inline
sets path to base file
Definition at line 60 of file starlightStandalone.h.
References _baseFileName, and baseFileName().
setConfigFileName()
void starlightStandalone::setConfigFileName (const std::string & configFileName) inline
sets path to config file
Definition at line 61 of file starlightStandalone.h.
References _configFileName, and configFileName().
setEventDataFileName()
void starlightStandalone::setEventDataFileName (const std::string & eventDataFileName) inline
sets path to output file
Definition at line 62 of file starlightStandalone.h.
References _eventDataFileName, and eventDataFileName().
Member Data Documentation
_baseFileName
std::string starlightStandalone::_baseFileName private
path to base filename
Definition at line 68 of file starlightStandalone.h.
Referenced by baseFileName(), init(), run(), and setBaseFileName().
_configFileName
std::string starlightStandalone::_configFileName private
path to configuration file
Definition at line 69 of file starlightStandalone.h.
Referenced by configFileName(), init(), and setConfigFileName().
_eventDataFileName
std::string starlightStandalone::_eventDataFileName private
path to output file
Definition at line 70 of file starlightStandalone.h.
Referenced by eventDataFileName(), run(), and setEventDataFileName().
_inputParameters
inputParameters* starlightStandalone::_inputParameters private
pointer to parameter instance
Definition at line 73 of file starlightStandalone.h.
Referenced by boostEvent(), init(), and run().
_nmbEventsPerFile
unsigned int starlightStandalone::_nmbEventsPerFile private
maximum number of events written to a single file (not yet implemented)
Definition at line 75 of file starlightStandalone.h.
Referenced by init(), and run().
_nmbEventsTot
unsigned int starlightStandalone::_nmbEventsTot private
total number of events to generate (taken from configuration file)
Definition at line 74 of file starlightStandalone.h.
Referenced by init(), and run().
_starlight
starlight* starlightStandalone::_starlight private
pointer to starlight instance
Definition at line 72 of file starlightStandalone.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
starlightStandalone.h
starlightStandalone.cpp