eSTARlight: twoPhotonLuminosity Class Reference
twoPhotonLuminosity Class Reference
#include <twophotonluminosity.h>
Classes
struct difflumiargs
Public Member Functions
twoPhotonLuminosity (const inputParameters &input, beam beam_1, beam beam_2)
~twoPhotonLuminosity ()
const beam & beam1 () const
returns beam particle 1
const beam & beam2 () const
returns beam particle 2
double probabilityOfBreakup (const double D) const
double cmsBoost () const
double beamLorentzGamma () const
void init ()
Private Member Functions
void twoPhotonDifferentialLuminosity ()
double D2LDMDY (double M, double Y, double &Normalize)
double D2LDMDY (double M, double Y) const
double integral (double Normalize)
double radmul (int N, double *Lower, double *Upper, int NIterMin, int NIterMax, double EPS, double *WK, int NIter, double &Result, double &ResErr, double &NFNEVL, double &Summary)
double integrand (double N, double X[15])
double Nphoton (double W, double gamma, double Rho)
Static Private Member Functions
static void * D2LDMDY_Threaded (void *a)
Private Attributes
double _W1
double _W2
double _gamma
const unsigned int _nWbins
const unsigned int _nYbins
const double _wMin
const double _yMin
const double _wMax
const double _yMax
const int _productionMode
const int _beamBreakupMode
const int _interferenceEnabled
const double _interferenceStrength
const double _maxPtInterference
const int _nmbPtBinsInterference
const int _xsecCalcMethod
const std::string _baseFileName
Detailed Description
Definition at line 43 of file twophotonluminosity.h.
Constructor & Destructor Documentation
twoPhotonLuminosity()
twoPhotonLuminosity::twoPhotonLuminosity (const inputParameters & input, beam beam_1, beam beam_2)
Definition at line 52 of file twophotonluminosity.cpp.
References twoPhotonDifferentialLuminosity().
~twoPhotonLuminosity()
twoPhotonLuminosity::~twoPhotonLuminosity ()
Definition at line 76 of file twophotonluminosity.cpp.
Member Function Documentation
beam1()
const beam& beamBeamSystem::beam1 () const inline inherited
returns beam particle 1
Definition at line 55 of file beambeamsystem.h.
References beamBeamSystem::_beam1.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), D2LDMDY(), photonNucleusCrossSection::e_getcsgA(), spectrumProtonNucleus::generateBreakupProbabilities(), photonNucleusCrossSection::getcsgA(), spectrum::getTransformedNofe(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), integral(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), Gammagammasingle::pp1(), Gammagammaleptonpair::pp_1(), starlightPythia::produceEvent(), starlightDpmJet::produceSingleEvent(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), photonNucleusCrossSection::sigma_A(), twoPhotonDifferentialLuminosity(), and photonNucleusLuminosity::vmsigmapt().
beam2()
const beam& beamBeamSystem::beam2 () const inline inherited
returns beam particle 2
Definition at line 56 of file beambeamsystem.h.
References beamBeamSystem::_beam2.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), D2LDMDY(), photonNucleusCrossSection::e_getcsgA(), spectrumProtonNucleus::generateBreakupProbabilities(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), integral(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_2(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), photonNucleusCrossSection::sigma_A(), twoPhotonDifferentialLuminosity(), and photonNucleusLuminosity::vmsigmapt().
beamLorentzGamma()
double beamBeamSystem::beamLorentzGamma () const inline inherited
Definition at line 62 of file beambeamsystem.h.
References beamBeamSystem::_beamLorentzGamma.
Referenced by spectrum::getTransformedNofe(), and starlightPythia::produceEvent().
cmsBoost()
double beamBeamSystem::cmsBoost () const inline inherited
Definition at line 60 of file beambeamsystem.h.
References beamBeamSystem::_cmsBoost.
D2LDMDY() [1/2]
double twoPhotonLuminosity::D2LDMDY (double M, double Y, double & Normalize) private
Definition at line 154 of file twophotonluminosity.cpp.
References _W1, _W2, starlightConstants::alpha, beamBeamSystem::beam1(), beamBeamSystem::beam2(), integral(), and nucleus::Z().
Referenced by D2LDMDY_Threaded(), and twoPhotonDifferentialLuminosity().
D2LDMDY() [2/2]
double twoPhotonLuminosity::D2LDMDY (double M, double Y) const private
Definition at line 173 of file twophotonluminosity.cpp.
References _gamma, beamBeamSystem::beam1(), beamBeamSystem::beam2(), starlightConstants::hbarc, nucleus::nuclearRadius(), beam::photonDensity(), starlightConstants::pi, and beamBeamSystem::probabilityOfBreakup().
D2LDMDY_Threaded()
void * twoPhotonLuminosity::D2LDMDY_Threaded (void * a) static private
Definition at line 250 of file twophotonluminosity.cpp.
References D2LDMDY(), twoPhotonLuminosity::difflumiargs::m, twoPhotonLuminosity::difflumiargs::res, twoPhotonLuminosity::difflumiargs::self, and twoPhotonLuminosity::difflumiargs::y.
init()
void beamBeamSystem::init () inherited
Definition at line 96 of file beambeamsystem.cpp.
References beamBeamSystem::_beam1, beamBeamSystem::_beam2, beamBeamSystem::_beamLorentzGamma, beamBeamSystem::_beamLorentzGamma1, beamBeamSystem::_beamLorentzGamma2, beamBeamSystem::_cmsBoost, beamBeamSystem::generateBreakupProbabilities(), and beam::setBeamLorentzGamma().
Referenced by beamBeamSystem::beamBeamSystem().
integral()
double twoPhotonLuminosity::integral (double Normalize) private
Definition at line 262 of file twophotonluminosity.cpp.
References _gamma, _W1, _W2, beamBeamSystem::beam1(), beamBeamSystem::beam2(), starlightConstants::hbarcmev, nucleus::nuclearRadius(), starlightConstants::pi, and radmul().
Referenced by D2LDMDY().
integrand()
double twoPhotonLuminosity::integrand (double N, double X[15]) private
Definition at line 643 of file twophotonluminosity.cpp.
References _gamma, _W1, _W2, starlightConstants::hbarcmev, Nphoton(), and beamBeamSystem::probabilityOfBreakup().
Referenced by radmul().
Nphoton()
double twoPhotonLuminosity::Nphoton (double W, double gamma, double Rho) private
Definition at line 657 of file twophotonluminosity.cpp.
References bessel::dbesk1(), and starlightConstants::pi.
Referenced by integrand().
probabilityOfBreakup()
double beamBeamSystem::probabilityOfBreakup (const double D) const inherited
Definition at line 112 of file beambeamsystem.cpp.
References beamBeamSystem::_beam1, beamBeamSystem::_beam2, beamBeamSystem::_breakupImpactParameterStep, beamBeamSystem::_breakupProbabilities, nucleus::A(), starlightConstants::hbarc, nucleus::nuclearRadius(), nucleus::rho0(), nucleus::thickness(), and nucleus::Z().
Referenced by D2LDMDY(), spectrum::generateBreakupProbabilities(), integrand(), photonNucleusCrossSection::photonFlux(), and photonNucleusLuminosity::pttablegen().
radmul()
double twoPhotonLuminosity::radmul (int N, double * Lower, double * Upper, int NIterMin, int NIterMax, double EPS, double * WK, int NIter, double & Result, double & ResErr, double & NFNEVL, double & Summary) private
Definition at line 419 of file twophotonluminosity.cpp.
References starlightConstants::F2, and integrand().
Referenced by integral().
twoPhotonDifferentialLuminosity()
void twoPhotonLuminosity::twoPhotonDifferentialLuminosity () private
Definition at line 81 of file twophotonluminosity.cpp.
References _baseFileName, _beamBreakupMode, _gamma, _interferenceEnabled, _interferenceStrength, _maxPtInterference, _nmbPtBinsInterference, _nWbins, _nYbins, _productionMode, _wMax, _wMin, _xsecCalcMethod, _yMax, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), D2LDMDY(), starlightConstants::deuteronSlopePar, and nucleus::Z().
Referenced by twoPhotonLuminosity().
Member Data Documentation
_baseFileName
const std::string twoPhotonLuminosity::_baseFileName private
Definition at line 89 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_beamBreakupMode
const int twoPhotonLuminosity::_beamBreakupMode private
Definition at line 83 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_gamma
double twoPhotonLuminosity::_gamma private
Definition at line 73 of file twophotonluminosity.h.
Referenced by D2LDMDY(), integral(), integrand(), and twoPhotonDifferentialLuminosity().
_interferenceEnabled
const int twoPhotonLuminosity::_interferenceEnabled private
Definition at line 84 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_interferenceStrength
const double twoPhotonLuminosity::_interferenceStrength private
Definition at line 85 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_maxPtInterference
const double twoPhotonLuminosity::_maxPtInterference private
Definition at line 86 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_nmbPtBinsInterference
const int twoPhotonLuminosity::_nmbPtBinsInterference private
Definition at line 87 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_nWbins
const unsigned int twoPhotonLuminosity::_nWbins private
Definition at line 75 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_nYbins
const unsigned int twoPhotonLuminosity::_nYbins private
Definition at line 76 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_productionMode
const int twoPhotonLuminosity::_productionMode private
Definition at line 82 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_W1
double twoPhotonLuminosity::_W1 private
Definition at line 71 of file twophotonluminosity.h.
Referenced by D2LDMDY(), integral(), and integrand().
_W2
double twoPhotonLuminosity::_W2 private
Definition at line 72 of file twophotonluminosity.h.
Referenced by D2LDMDY(), integral(), and integrand().
_wMax
const double twoPhotonLuminosity::_wMax private
Definition at line 80 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_wMin
const double twoPhotonLuminosity::_wMin private
Definition at line 78 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_xsecCalcMethod
const int twoPhotonLuminosity::_xsecCalcMethod private
Definition at line 88 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_yMax
const double twoPhotonLuminosity::_yMax private
Definition at line 81 of file twophotonluminosity.h.
Referenced by twoPhotonDifferentialLuminosity().
_yMin
const double twoPhotonLuminosity::_yMin private
Definition at line 79 of file twophotonluminosity.h.
The documentation for this class was generated from the following files:
twophotonluminosity.h
twophotonluminosity.cpp