eSTARlight: randomGenerator Class Reference
randomGenerator Class Reference
#include <randomgenerator.h>
Public Member Functions
void SetSeed (unsigned int seed)
double Rndom (int i=0)
Private Attributes
unsigned int _Mt [624]
int _count624
Detailed Description
Definition at line 38 of file randomgenerator.h.
Member Function Documentation
Rndom()
double randomGenerator::Rndom (int i = 0)
Definition at line 107 of file randomgenerator.cpp.
Referenced by spectrum::drawKdouble(), spectrum::drawKsingle(), Gammaavectormeson::e_produceEvent(), Gammagammaleptonpair::Gammagammaleptonpair(), Gammaavectormeson::getTheta(), Gammaavectormeson::momenta(), Gammagammaleptonpair::pairMomentum(), Gammagammasingle::parentMomentum(), Gammagammasingle::pickw(), Gammagammaleptonpair::pickw(), Gammaavectormeson::pickwEgamq2(), Gammaavectormeson::pickwy(), Gammagammasingle::picky(), Gammagammaleptonpair::picky(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), starlightDpmJet::produceDoubleEvent(), Gammagammaleptonpair::produceEvent(), Gammaavectormeson::produceEvent(), Gammagammasingle::produceEvent(), Gammaavectormeson::pTgamma(), nBodyPhaseSpaceGen::random(), Gammagammaleptonpair::tauDecay(), Gammaavectormeson::twoBodyDecay(), Gammagammaleptonpair::twoBodyDecay(), Gammagammasingle::twoBodyDecay(), and Gammaavectormeson::vmpt().
SetSeed()
void randomGenerator::SetSeed (unsigned int seed)
Definition at line 84 of file randomgenerator.cpp.
Referenced by eventChannel::eventChannel().
Member Data Documentation
_count624
int randomGenerator::_count624 private
Definition at line 46 of file randomgenerator.h.
_Mt
unsigned int randomGenerator::_Mt[624] private
Definition at line 45 of file randomgenerator.h.
The documentation for this class was generated from the following files:
randomgenerator.h
randomgenerator.cpp