eSTARlight: fileWriter Class Reference
fileWriter Class Reference
#include <filewriter.h>
Public Member Functions
fileWriter ()
fileWriter (const std::string &fileName)
virtual ~fileWriter ()
int open ()
int open (const std::string &fileName)
int close ()
void setFileName (const std::string &fileName)
Protected Attributes
std::string _fileName
std::ofstream _fileStream
Detailed Description
Definition at line 43 of file filewriter.h.
Constructor & Destructor Documentation
fileWriter() [1/2]
fileWriter::fileWriter ()
Default constructor
Definition at line 44 of file filewriter.cpp.
fileWriter() [2/2]
fileWriter::fileWriter (const std::string & fileName)
Constructor with filename
Definition at line 50 of file filewriter.cpp.
~fileWriter()
fileWriter::~fileWriter () virtual
Destructor
Definition at line 56 of file filewriter.cpp.
Member Function Documentation
close()
int fileWriter::close ()
close the file
Definition at line 84 of file filewriter.cpp.
References _fileStream.
Referenced by e_starlightStandalone::run().
open() [1/2]
int fileWriter::open ()
open the file
Definition at line 60 of file filewriter.cpp.
References _fileName, and _fileStream.
Referenced by open(), and e_starlightStandalone::run().
open() [2/2]
int fileWriter::open (const std::string & fileName)
open file with given filename
Definition at line 77 of file filewriter.cpp.
References _fileName, and open().
setFileName()
void fileWriter::setFileName (const std::string & fileName) inline
Set the filename we're writing to
Definition at line 66 of file filewriter.h.
References _fileName.
Member Data Documentation
_fileName
std::string fileWriter::_fileName protected
The file name
Definition at line 71 of file filewriter.h.
Referenced by open(), and setFileName().
_fileStream
std::ofstream fileWriter::_fileStream protected
The file stream
Definition at line 74 of file filewriter.h.
Referenced by close(), open(), eventFileWriter::writeEvent(), and eventFileWriter::writeInit().
The documentation for this class was generated from the following files:
filewriter.h
filewriter.cpp