eSTARlight: starlight Class Reference
starlight Class Reference
#include <starlight.h>
Public Member Functions
starlight ()
~starlight ()
bool init ()
upcEvent produceEvent ()
std::string baseFileName () const
unsigned long nmbAttempts () const
unsigned long nmbAccepted () const
double getTotalCrossSection () const
void setInputParameters (inputParameters *inputParams)
Private Member Functions
bool luminosityTableIsValid () const
bool createEventChannel ()
Private Attributes
beamBeamSystem * _beamSystem
eventChannel * _eventChannel
unsigned int _nmbEventsPerFile
std::string _baseFileName
std::string _lumLookUpTableFileName
bool _isInitialised
inputParameters * _inputParameters
Detailed Description
Definition at line 49 of file starlight.h.
Constructor & Destructor Documentation
starlight()
starlight::starlight ()
Definition at line 70 of file starlight.cpp.
~starlight()
starlight::~starlight ()
Definition at line 79 of file starlight.cpp.
Member Function Documentation
baseFileName()
std::string starlight::baseFileName () const inline
Definition at line 60 of file starlight.h.
References _baseFileName.
createEventChannel()
bool starlight::createEventChannel () private
Definition at line 274 of file starlight.cpp.
References _beamSystem, _eventChannel, _inputParameters, starlightConstants::A2, starlightConstants::AXION, starlightConstants::ELECTRON, starlightConstants::ETA, starlightConstants::ETAC, starlightConstants::ETAPRIME, starlightConstants::F0, starlightConstants::F2, starlightConstants::F2PRIME, starlightConstants::FOURPRONG, inputParameters::interactionType(), starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::MUON, starlightConstants::OMEGA, starlightConstants::PHI, starlightConstants::PHOTONPOMERONINCOHERENT, starlightConstants::PHOTONPOMERONNARROW, starlightConstants::PHOTONPOMERONWIDE, printWarn, inputParameters::prodParticleType(), starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::TAUON, starlightConstants::TAUONDECAY, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, starlightConstants::UPSILON_mumu, and starlightConstants::ZOVERZ03.
Referenced by init().
getTotalCrossSection()
double starlight::getTotalCrossSection () const inline
Definition at line 63 of file starlight.h.
References _eventChannel, and eventChannel::getTotalChannelCrossSection().
Referenced by starlightStandalone::run().
init()
bool starlight::init ()
Definition at line 84 of file starlight.cpp.
References _baseFileName, _beamSystem, _eventChannel, _inputParameters, _isInitialised, _lumLookUpTableFileName, _nmbEventsPerFile, inputParameters::baseFileName(), beamBeamSystem::beam1(), inputParameters::beam1A(), inputParameters::beam1Z(), beamBeamSystem::beam2(), inputParameters::beam2A(), inputParameters::beam2Z(), createEventChannel(), inputParameters::interactionType(), luminosityTableIsValid(), inputParameters::maxGammaEnergy(), inputParameters::minGammaEnergy(), inputParameters::nmbEvents(), starlightConstants::PHOTONPHOTON, starlightConstants::PHOTONPOMERONINCOHERENT, starlightConstants::PHOTONPOMERONNARROW, starlightConstants::PHOTONPOMERONWIDE, starlightConstants::PHOTONUCLEARDOUBLE, starlightConstants::PHOTONUCLEARSINGLE, starlightConstants::PHOTONUCLEARSINGLEPA, starlightConstants::PHOTONUCLEARSINGLEPAPY, printErr, printInfo, printWarn, inputParameters::pythiaFullEventRecord(), and inputParameters::pythiaParams().
Referenced by starlightStandalone::init().
luminosityTableIsValid()
bool starlight::luminosityTableIsValid () const private
Definition at line 222 of file starlight.cpp.
References _inputParameters, _lumLookUpTableFileName, starlightConstants::deuteronSlopePar, inputParameters::parameterValueKey(), printInfo, and inputParameters::randomSeed().
Referenced by init().
nmbAccepted()
unsigned long starlight::nmbAccepted () const inline
Definition at line 62 of file starlight.h.
References _eventChannel, and eventChannel::nmbAccepted().
Referenced by starlightStandalone::run().
nmbAttempts()
unsigned long starlight::nmbAttempts () const inline
Definition at line 61 of file starlight.h.
References _eventChannel, and eventChannel::nmbAttempts().
Referenced by starlightStandalone::run().
produceEvent()
upcEvent starlight::produceEvent ()
Definition at line 211 of file starlight.cpp.
References _eventChannel, _isInitialised, printErr, and eventChannel::produceEvent().
Referenced by starlightStandalone::run().
setInputParameters()
void starlight::setInputParameters (inputParameters * inputParams) inline
Definition at line 64 of file starlight.h.
References _inputParameters.
Referenced by starlightStandalone::init().
Member Data Documentation
_baseFileName
std::string starlight::_baseFileName private
Definition at line 75 of file starlight.h.
Referenced by baseFileName(), and init().
_beamSystem
beamBeamSystem* starlight::_beamSystem private
Definition at line 72 of file starlight.h.
Referenced by createEventChannel(), and init().
_eventChannel
eventChannel* starlight::_eventChannel private
Definition at line 73 of file starlight.h.
Referenced by createEventChannel(), getTotalCrossSection(), init(), nmbAccepted(), nmbAttempts(), and produceEvent().
_inputParameters
inputParameters* starlight::_inputParameters private
Definition at line 78 of file starlight.h.
Referenced by createEventChannel(), init(), luminosityTableIsValid(), and setInputParameters().
_isInitialised
bool starlight::_isInitialised private
Definition at line 77 of file starlight.h.
Referenced by init(), and produceEvent().
_lumLookUpTableFileName
std::string starlight::_lumLookUpTableFileName private
Definition at line 76 of file starlight.h.
Referenced by init(), and luminosityTableIsValid().
_nmbEventsPerFile
unsigned int starlight::_nmbEventsPerFile private
Definition at line 74 of file starlight.h.
Referenced by init().
The documentation for this class was generated from the following files:
starlight.h
starlight.cpp