eSTARlight: parameterlist Class Reference
parameterlist Class Reference
#include <inputParameters.h>
Public Member Functions
parameterlist ()
void add (parameterbase *p)
std::string validationKey ()
Private Attributes
std::vector< parameterbase * > _parameters
Detailed Description
Definition at line 48 of file inputParameters.h.
Constructor & Destructor Documentation
parameterlist()
parameterlist::parameterlist () inline
Definition at line 52 of file inputParameters.h.
Member Function Documentation
add()
void parameterlist::add (parameterbase * p) inline
Definition at line 54 of file inputParameters.h.
References _parameters.
Referenced by parameterbase::parameterbase().
validationKey()
std::string parameterlist::validationKey () inline
Definition at line 161 of file inputParameters.h.
References _parameters.
Referenced by operator<<(), and inputParameters::parameterValueKey().
Member Data Documentation
_parameters
std::vector<parameterbase*> parameterlist::_parameters private
Definition at line 65 of file inputParameters.h.
Referenced by add(), and validationKey().
The documentation for this class was generated from the following file:
inputParameters.h