eSTARlight: beam Class Reference
beam Class Reference
#include <beam.h>
Public Member Functions
beam (const int Z, const int A, const int productionMode, const double beamLorentzGamma)
~beam ()
double photonDensity (const double impactparameter, const double photonEnergy) const
calculates photon density (number of photons / (energy * area))
double rapidity () const
void setBeamLorentzGamma (double gamma)
void init ()
int Z () const
returns atomic number of nucleus
int A () const
returns nucleon number of nucleus
int productionMode () const
double formFactor (const double t) const
double dipoleFormFactor (const double t, const double t0) const
double thickness (const double b) const
double nuclearRadius () const
double rho0 () const
Protected Attributes
double _beamLorentzGamma
Lorentz gamma factor of beams in collider frame (from inputParameters)
Detailed Description
Definition at line 41 of file beam.h.
Constructor & Destructor Documentation
beam()
beam::beam (const int Z, const int A, const int productionMode, const double beamLorentzGamma)
Definition at line 48 of file beam.cpp.
~beam()
beam::~beam ()
Definition at line 57 of file beam.cpp.
Member Function Documentation
A()
int nucleus::A () const inline inherited
returns nucleon number of nucleus
Definition at line 55 of file nucleus.h.
References nucleus::_A.
Referenced by e_narrowResonanceCrossSection::crossSectionCalculation(), wideResonanceCrossSection::crossSectionCalculation(), e_wideResonanceCrossSection::crossSectionCalculation(), incoherentVMCrossSection::crossSectionCalculation(), narrowResonanceCrossSection::crossSectionCalculation(), photonNucleusCrossSection::e_getcsgA(), beamBeamSystem::generateBreakupProbabilities(), photonNucleusCrossSection::getcsgA(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), e_narrowResonanceCrossSection::makeGammaPQ2dependence(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), Gammaavectormeson::pickwy(), beamBeamSystem::probabilityOfBreakup(), beamBeamSystem::probabilityOfHadronBreakup(), beamBeamSystem::probabilityOfPhotonBreakup(), Gammaavectormeson::pTgamma(), photonNucleusCrossSection::sigma_A(), and twoPhotonLuminosity::twoPhotonDifferentialLuminosity().
dipoleFormFactor()
double nucleus::dipoleFormFactor (const double t, const double t0) const inherited
Definition at line 155 of file nucleus.cpp.
Referenced by Gammaavectormeson::momenta().
formFactor()
double nucleus::formFactor (const double t) const inherited
Definition at line 128 of file nucleus.cpp.
References nucleus::_A, nucleus::_Z, starlightConstants::hbarc, and nucleus::nuclearRadius().
Referenced by photonNucleusCrossSection::e_getcsgA(), photonNucleusCrossSection::getcsgA(), Gammaavectormeson::momenta(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), and photonNucleusLuminosity::vmsigmapt().
init()
void nucleus::init () inherited
Definition at line 57 of file nucleus.cpp.
References nucleus::_A, nucleus::_Radius, nucleus::_rho0, nucleus::_Z, and printWarn.
Referenced by nucleus::nucleus().
nuclearRadius()
double nucleus::nuclearRadius () const inline inherited
Definition at line 67 of file nucleus.h.
References nucleus::_Radius.
Referenced by twoPhotonLuminosity::D2LDMDY(), nucleus::formFactor(), beamBeamSystem::generateBreakupProbabilities(), twoPhotonLuminosity::integral(), Gammaavectormeson::momenta(), photonNucleusCrossSection::photonFlux(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), beamBeamSystem::probabilityOfBreakup(), beamBeamSystem::probabilityOfHadronBreakup(), Gammaavectormeson::pTgamma(), photonNucleusLuminosity::pttablegen(), nucleus::rws(), and photonNucleusLuminosity::vmsigmapt().
photonDensity()
double beam::photonDensity (const double impactparameter, const double photonEnergy) const
calculates photon density (number of photons / (energy * area))
Definition at line 62 of file beam.cpp.
References _beamLorentzGamma, starlightConstants::alpha, bessel::dbesk1(), starlightConstants::hbarc, starlightConstants::pi, printWarn, and nucleus::Z().
Referenced by twoPhotonLuminosity::D2LDMDY(), spectrum::getTransformedNofe(), photonNucleusCrossSection::photonFlux(), and photonNucleusLuminosity::pttablegen().
productionMode()
int nucleus::productionMode () const inline inherited
Definition at line 56 of file nucleus.h.
References nucleus::_productionMode.
rapidity()
double beam::rapidity () const inline
Definition at line 56 of file beam.h.
References _beamLorentzGamma.
Referenced by starlightDpmJet::produceSingleEvent().
rho0()
double nucleus::rho0 () const inline inherited
Definition at line 68 of file nucleus.h.
References nucleus::_rho0.
Referenced by beamBeamSystem::probabilityOfBreakup(), and photonNucleusCrossSection::sigma_A().
setBeamLorentzGamma()
void beam::setBeamLorentzGamma (double gamma) inline
Definition at line 58 of file beam.h.
References _beamLorentzGamma.
Referenced by beamBeamSystem::init().
thickness()
double nucleus::thickness (const double b) const inherited
Definition at line 163 of file nucleus.cpp.
References nucleus::rws().
Referenced by spectrumProtonNucleus::generateBreakupProbabilities(), beamBeamSystem::probabilityOfBreakup(), and photonNucleusCrossSection::sigma_A().
Z()
int nucleus::Z () const inline inherited
returns atomic number of nucleus
Definition at line 54 of file nucleus.h.
References nucleus::_Z.
Referenced by twoPhotonLuminosity::D2LDMDY(), spectrumProtonNucleus::generateBreakupProbabilities(), beamBeamSystem::generateBreakupProbabilities(), incoherentPhotonNucleusLuminosity::incoherentPhotonNucleusDifferentialLuminosity(), photonDensity(), photonNucleusCrossSection::photonFlux(), photonNucleusLuminosity::photonNucleusDifferentialLuminosity(), photonElectronLuminosity::photonNucleusDifferentialLuminosity(), beamBeamSystem::probabilityOfBreakup(), beamBeamSystem::probabilityOfPhotonBreakup(), starlightPythia::produceEvent(), and twoPhotonLuminosity::twoPhotonDifferentialLuminosity().
Member Data Documentation
_beamLorentzGamma
double beam::_beamLorentzGamma protected
Lorentz gamma factor of beams in collider frame (from inputParameters)
Definition at line 61 of file beam.h.
Referenced by photonDensity(), rapidity(), and setBeamLorentzGamma().
The documentation for this class was generated from the following files:
beam.h
beam.cpp