eSTARlight: Gammaavectormeson Class Reference
Gammaavectormeson Class Reference
#include <gammaavm.h>
Public Member Functions
Gammaavectormeson (const inputParameters &ipnut, beamBeamSystem &bbsystem)
virtual ~Gammaavectormeson ()
starlightConstants::event produceEvent (int &ievent)
upcEvent produceEvent ()
eXEvent e_produceEvent ()
void pickwy (double &W, double &Y)
void pickwEgamq2 (double &W, double &cmsEgamma, double &targetEgamma, double &Q2, double &gamma_pz, double &gamma_pt, double &E_prime, double &cos_theta_e)
void momenta (double W, double Y, double &E, double &px, double &py, double &pz, int &tcheck)
void momenta (double W, double Egam, double Q2, double gamma_pz, double gamma_pt, double &rapidity, double &E, double &px, double &py, double &pz, double &t_px, double &t_py, double &t_pz, double &t_E, double &e_phi, int &tcheck)
double pTgamma (double E)
void vmpt (double W, double Y, double &E, double &px, double &py, double &pz, int &tcheck)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
void twoBodyDecay (starlightConstants::particleTypeEnum &ipid, double W, double px0, double py0, double pz0, double spin_element, double &px1, double &py1, double &pz1, double &px2, double &py2, double &pz2, int &iFbadevent)
bool fourBodyDecay (starlightConstants::particleTypeEnum &ipid, const double E, const double W, const double *p, lorentzVector *decayMoms, int &iFbadevent)
double getMass ()
double getWidth ()
virtual double getTheta (starlightConstants::particleTypeEnum ipid)
virtual double getTheta (starlightConstants::particleTypeEnum ipid, double r_04_00)
double getSpinMatrixElement (double W, double Q2, double epsilon)
double getSpin ()
virtual double getDaughterMass (starlightConstants::particleTypeEnum &ipid)
double pseudoRapidity (double px, double py, double pz)
unsigned long nmbAttempts () const
returns number of attempted events
unsigned long nmbAccepted () const
returns number of accepted events
double getTotalChannelCrossSection () const
void setTotalChannelCrossSection (double sigma)
void read ()
void e_read ()
Static Public Member Functions
static void transform (const double betax, const double betay, const double betaz, double &E, double &px, double &py, double &pz, int &iFbadevent)
Lorentz-transforms given 4-vector.
Public Attributes
double _VMbslope
beamBeamSystem _bbs
randomGenerator _randy
double * _Warray
double * _BWarray
double * _Yarray
double ** _Farray
double ** _Farray1
double ** _Farray2
double ** _f_WYarray
double ** _g_Earray
std::vector< std::pair< double, std::vector< double > > > * _g_EQ2array
double _f_max
double _f_max1
double _f_max2
double _f_WYmax
double _g_Emax
double _g_EQ2max
double _fptarray [500][500]
double _bwnormsave
Protected Attributes
unsigned long _nmbAttempts
number of attempted events
unsigned long _nmbAccepted
number of accepted events
bool _ptCutEnabled
en/disables cut in pt
double _ptCutMin
minimum pt, if cut is enabled
double _ptCutMax
maximum pt, if cut is enabled
bool _etaCutEnabled
en/disables cut in eta
double _etaCutMin
minimum eta, if cut is enabled
double _etaCutMax
maximum eta, if cut is enabled
double _totalChannelCrossSection
const int _ReadInputNPT
const int _ReadInputnumy
const int _ReadInputnumw
const int _ReadInputnumega
const int _ReadInputnumQ2
const int _ReadInputgg_or_gP
const int _ReadInputinterferencemode
const std::string _baseFileName
Private Member Functions
std::string gammaTableParse (int ii, int jj)
Private Attributes
starlightConstants::particleTypeEnum _VMpidtest
int _VMnumw
int _VMnumy
int _VMnumega
int _VMnumQ2
int _VMinterferencemode
int _ProductionMode
double _targetMaxPhotonEnergy
double _targetMinPhotonEnergy
double _cmsMaxPhotonEnergy
double _cmsMinPhotonEnergy
double _beamLorentzGamma
double _targetRadius
int _TargetBeam
int N0
int N1
int N2
double _VMgamma_em
double _VMNPT
double _VMWmax
double _VMWmin
double _VMYmax
double _VMYmin
double _mass
double _width
double _VMptmax
double _VMdpt
int _bslopeDef
double _bslopeVal
double _pEnergy
int _beamNucleus
double _eEnergy
nBodyPhaseSpaceGen * _phaseSpaceGen
photonNucleusCrossSection * _dummy_pncs
double _angular_max [100][200]
Detailed Description
Definition at line 51 of file gammaavm.h.
Constructor & Destructor Documentation
Gammaavectormeson()
Gammaavectormeson::Gammaavectormeson (const inputParameters & ipnut, beamBeamSystem & bbsystem)
Definition at line 52 of file gammaavm.cpp.
References _angular_max, _beamLorentzGamma, _beamNucleus, _bslopeDef, _bslopeVal, _cmsMaxPhotonEnergy, _cmsMinPhotonEnergy, _dummy_pncs, _eEnergy, _pEnergy, _phaseSpaceGen, _ProductionMode, eventChannel::_randy, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _targetRadius, _VMbslope, _VMdpt, _VMgamma_em, _VMinterferencemode, _VMNPT, _VMnumega, _VMnumQ2, _VMnumw, _VMpidtest, _VMptmax, _VMWmax, _VMWmin, inputParameters::beam2A(), inputParameters::beamLorentzGamma(), inputParameters::bslopeDefinition(), inputParameters::bslopeValue(), inputParameters::cmsMaxPhotonEnergy(), inputParameters::cmsMinPhotonEnergy(), inputParameters::electronEnergy(), starlightConstants::FOURPRONG, inputParameters::interferenceEnabled(), inputParameters::maxPtInterference(), inputParameters::maxW(), inputParameters::minW(), N0, N1, N2, inputParameters::nmbEnergyBins(), inputParameters::nmbGammaQ2Bins(), inputParameters::nmbPtBinsInterference(), inputParameters::nmbWBins(), starlightConstants::pi, inputParameters::prodParticleType(), inputParameters::productionMode(), inputParameters::protonEnergy(), inputParameters::ptBinWidthInterference(), inputParameters::targetMaxPhotonEnergy(), inputParameters::targetMinPhotonEnergy(), and inputParameters::targetRadius().
~Gammaavectormeson()
Gammaavectormeson::~Gammaavectormeson () virtual
Definition at line 115 of file gammaavm.cpp.
References _dummy_pncs, and _phaseSpaceGen.
Member Function Documentation
e_produceEvent()
eXEvent Gammaavectormeson::e_produceEvent () virtual
Implements eventChannel.
Definition at line 1348 of file gammaavm.cpp.
References _beamNucleus, _eEnergy, eventChannel::_etaCutEnabled, eventChannel::_etaCutMax, eventChannel::_etaCutMin, eventChannel::_nmbAccepted, eventChannel::_nmbAttempts, _pEnergy, eventChannel::_ptCutEnabled, eventChannel::_ptCutMax, eventChannel::_ptCutMin, eventChannel::_randy, getDaughterMass(), getSpinMatrixElement(), momenta(), starlightConstants::pi, pickwEgamq2(), starlightConstants::protonMass, pseudoRapidity(), randomGenerator::Rndom(), twoBodyDecay(), and starlightConstants::UNKNOWN.
e_read()
void readLuminosity::e_read () inherited
Definition at line 208 of file readinluminosity.cpp.
References readLuminosity::_baseFileName, readLuminosity::_BWarray, readLuminosity::_bwnormsave, readLuminosity::_f_WYarray, readLuminosity::_f_WYmax, readLuminosity::_g_Earray, readLuminosity::_g_Emax, readLuminosity::_g_EQ2array, readLuminosity::_g_EQ2max, readLuminosity::_ReadInputnumega, readLuminosity::_ReadInputnumQ2, readLuminosity::_ReadInputnumw, readLuminosity::_ReadInputnumy, readLuminosity::_Warray, and readLuminosity::_Yarray.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), and e_Gammaawidevm::e_Gammaawidevm().
fourBodyDecay()
bool Gammaavectormeson::fourBodyDecay (starlightConstants::particleTypeEnum & ipid, const double E, const double W, const double * p, lorentzVector * decayMoms, int & iFbadevent)
Definition at line 306 of file gammaavm.cpp.
Referenced by produceEvent().
gammaTableParse()
string Gammaavectormeson::gammaTableParse (int ii, int jj) private
Definition at line 1470 of file gammaavm.cpp.
getDaughterMass()
double Gammaavectormeson::getDaughterMass (starlightConstants::particleTypeEnum & ipid) virtual
Definition at line 351 of file gammaavm.cpp.
References _VMpidtest, starlightConstants::ELECTRON, starlightConstants::FOURPRONG, starlightConstants::JPSI, starlightConstants::JPSI2S, starlightConstants::JPSI2S_ee, starlightConstants::JPSI2S_mumu, starlightConstants::JPSI_ee, starlightConstants::JPSI_mumu, starlightConstants::KAONCHARGE, starlightConstants::kaonChargedMass, starlightConstants::mel, starlightConstants::MUON, starlightConstants::muonMass, starlightConstants::OMEGA, starlightConstants::PHI, starlightConstants::PION, starlightConstants::pionChargedMass, starlightConstants::RHO, starlightConstants::RHOZEUS, starlightConstants::UPSILON, starlightConstants::UPSILON2S, starlightConstants::UPSILON2S_ee, starlightConstants::UPSILON2S_mumu, starlightConstants::UPSILON3S, starlightConstants::UPSILON3S_ee, starlightConstants::UPSILON3S_mumu, starlightConstants::UPSILON_ee, and starlightConstants::UPSILON_mumu.
Referenced by e_produceEvent(), produceEvent(), and twoBodyDecay().
getMass()
double Gammaavectormeson::getMass ()
Definition at line 516 of file gammaavm.cpp.
References _mass.
getSpin()
double Gammaavectormeson::getSpin ()
Definition at line 523 of file gammaavm.cpp.
getSpinMatrixElement()
double Gammaavectormeson::getSpinMatrixElement (double W, double Q2, double epsilon)
Definition at line 499 of file gammaavm.cpp.
References starlightConstants::pi.
Referenced by e_produceEvent().
getTheta() [1/2]
double Gammaavectormeson::getTheta (starlightConstants::particleTypeEnum ipid) virtual
Definition at line 416 of file gammaavm.cpp.
References eventChannel::_randy, starlightConstants::ELECTRON, starlightConstants::KAONCHARGE, starlightConstants::MUON, starlightConstants::pi, starlightConstants::PION, and randomGenerator::Rndom().
Referenced by twoBodyDecay().
getTheta() [2/2]
double Gammaavectormeson::getTheta (starlightConstants::particleTypeEnum ipid, double r_04_00) virtual
Definition at line 457 of file gammaavm.cpp.
References eventChannel::_randy, starlightConstants::ELECTRON, starlightConstants::KAONCHARGE, starlightConstants::MUON, starlightConstants::pi, starlightConstants::PION, and randomGenerator::Rndom().
getTotalChannelCrossSection()
double eventChannel::getTotalChannelCrossSection () const inline inherited
Definition at line 79 of file eventchannel.h.
References eventChannel::_totalChannelCrossSection.
Referenced by starlight::getTotalCrossSection(), and e_starlight::getTotalCrossSection().
getWidth()
double Gammaavectormeson::getWidth ()
Definition at line 509 of file gammaavm.cpp.
References _width.
momenta() [1/2]
void Gammaavectormeson::momenta (double W, double Y, double & E, double & px, double & py, double & pz, int & tcheck)
Definition at line 530 of file gammaavm.cpp.
References eventChannel::_bbs, _bslopeDef, _bslopeVal, _pEnergy, _ProductionMode, eventChannel::_randy, _TargetBeam, _VMbslope, _VMgamma_em, _VMpidtest, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::dipoleFormFactor(), nucleus::formFactor(), starlightConstants::hbarc, N0, nucleus::nuclearRadius(), starlightConstants::OMEGA, starlightConstants::pi, pTgamma(), starlightConstants::RHO, starlightConstants::RHOZEUS, and randomGenerator::Rndom().
Referenced by e_produceEvent(), and produceEvent().
momenta() [2/2]
void Gammaavectormeson::momenta (double W, double Egam, double Q2, double gamma_pz, double gamma_pt, double & rapidity, double & E, double & px, double & py, double & pz, double & t_px, double & t_py, double & t_pz, double & t_E, double & e_phi, int & tcheck)
Definition at line 701 of file gammaavm.cpp.
References eventChannel::_bbs, _beamNucleus, _bslopeDef, _bslopeVal, _pEnergy, _ProductionMode, eventChannel::_randy, _VMbslope, _VMgamma_em, _VMpidtest, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::dipoleFormFactor(), nucleus::formFactor(), starlightConstants::hbarc, N0, nucleus::nuclearRadius(), starlightConstants::OMEGA, starlightConstants::pi, starlightConstants::protonMass, starlightConstants::RHO, starlightConstants::RHOZEUS, and randomGenerator::Rndom().
nmbAccepted()
unsigned long eventChannel::nmbAccepted () const inline inherited
returns number of accepted events
Definition at line 57 of file eventchannel.h.
References eventChannel::_nmbAccepted.
Referenced by starlight::nmbAccepted(), and e_starlight::nmbAccepted().
nmbAttempts()
unsigned long eventChannel::nmbAttempts () const inline inherited
returns number of attempted events
Definition at line 56 of file eventchannel.h.
References eventChannel::_nmbAttempts.
Referenced by starlight::nmbAttempts(), and e_starlight::nmbAttempts().
pickwEgamq2()
void Gammaavectormeson::pickwEgamq2 (double & W, double & cmsEgamma, double & targetEgamma, double & Q2, double & gamma_pz, double & gamma_pt, double & E_prime, double & cos_theta_e)
Definition at line 1255 of file gammaavm.cpp.
References _beamLorentzGamma, readLuminosity::_BWarray, _cmsMinPhotonEnergy, _eEnergy, readLuminosity::_f_WYarray, readLuminosity::_g_EQ2array, eventChannel::_randy, _targetMaxPhotonEnergy, _targetMinPhotonEnergy, _targetRadius, _VMnumega, _VMnumQ2, _VMnumw, _VMWmax, _VMWmin, N0, starlightConstants::pionChargedMass, and randomGenerator::Rndom().
Referenced by e_produceEvent().
pickwy()
void Gammaavectormeson::pickwy (double & W, double & Y)
Definition at line 125 of file gammaavm.cpp.
References eventChannel::_bbs, readLuminosity::_Farray, readLuminosity::_Farray1, _ProductionMode, eventChannel::_randy, _TargetBeam, _VMnumw, _VMnumy, _VMWmax, _VMWmin, _VMYmax, _VMYmin, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), N0, N1, N2, starlightConstants::pionChargedMass, and randomGenerator::Rndom().
Referenced by produceEvent().
produceEvent() [1/2]
starlightConstants::event Gammaavectormeson::produceEvent (int & ievent) virtual
Implements eventChannel.
Definition at line 1024 of file gammaavm.cpp.
produceEvent() [2/2]
upcEvent Gammaavectormeson::produceEvent () virtual
Implements eventChannel.
Definition at line 1032 of file gammaavm.cpp.
References eventChannel::_etaCutEnabled, eventChannel::_etaCutMax, eventChannel::_etaCutMin, eventChannel::_nmbAccepted, eventChannel::_nmbAttempts, eventChannel::_ptCutEnabled, eventChannel::_ptCutMax, eventChannel::_ptCutMin, eventChannel::_randy, _VMinterferencemode, _VMpidtest, fourBodyDecay(), starlightConstants::FOURPRONG, getDaughterMass(), momenta(), pickwy(), pseudoRapidity(), randomGenerator::Rndom(), twoBodyDecay(), starlightConstants::UNKNOWN, and vmpt().
pseudoRapidity()
double Gammaavectormeson::pseudoRapidity (double px, double py, double pz)
Definition at line 1156 of file gammaavm.cpp.
Referenced by e_produceEvent(), and produceEvent().
pTgamma()
double Gammaavectormeson::pTgamma (double E)
Definition at line 829 of file gammaavm.cpp.
References eventChannel::_bbs, _ProductionMode, eventChannel::_randy, _TargetBeam, _VMgamma_em, nucleus::A(), beamBeamSystem::beam1(), beamBeamSystem::beam2(), nucleus::formFactor(), starlightConstants::hbarc, nucleus::nuclearRadius(), starlightConstants::pi, and randomGenerator::Rndom().
Referenced by momenta().
read()
void readLuminosity::read () inherited
Definition at line 79 of file readinluminosity.cpp.
References readLuminosity::_baseFileName, readLuminosity::_bwnormsave, readLuminosity::_f_max, readLuminosity::_f_max1, readLuminosity::_f_max2, readLuminosity::_Farray, readLuminosity::_Farray1, readLuminosity::_Farray2, readLuminosity::_fptarray, readLuminosity::_ReadInputgg_or_gP, readLuminosity::_ReadInputinterferencemode, readLuminosity::_ReadInputNPT, readLuminosity::_ReadInputnumw, readLuminosity::_ReadInputnumy, readLuminosity::_Warray, readLuminosity::_Yarray, starlightLimits::MAXWBINS, and starlightLimits::MAXYBINS.
Referenced by Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), Gammagammaleptonpair::Gammagammaleptonpair(), and Gammagammasingle::Gammagammasingle().
setTotalChannelCrossSection()
void eventChannel::setTotalChannelCrossSection (double sigma) inline inherited
Definition at line 80 of file eventchannel.h.
References eventChannel::_totalChannelCrossSection.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), Gammagammasingle::singleCrossSection(), and Gammagammaleptonpair::twoLeptonCrossSection().
transform()
void eventChannel::transform (const double betax, const double betay, const double betaz, double & E, double & px, double & py, double & pz, int & iFbadevent) static inherited
Lorentz-transforms given 4-vector.
Definition at line 69 of file eventchannel.cpp.
Referenced by Gammagammaleptonpair::tauDecay(), twoBodyDecay(), Gammagammasingle::twoBodyDecay(), and Gammagammaleptonpair::twoBodyDecay().
twoBodyDecay() [1/2]
void Gammaavectormeson::twoBodyDecay (starlightConstants::particleTypeEnum & ipid, double W, double px0, double py0, double pz0, double & px1, double & py1, double & pz1, double & px2, double & py2, double & pz2, int & iFbadevent)
Definition at line 179 of file gammaavm.cpp.
References eventChannel::_randy, getDaughterMass(), getTheta(), starlightConstants::pi, randomGenerator::Rndom(), and eventChannel::transform().
Referenced by e_produceEvent(), and produceEvent().
twoBodyDecay() [2/2]
void Gammaavectormeson::twoBodyDecay (starlightConstants::particleTypeEnum & ipid, double W, double px0, double py0, double pz0, double spin_element, double & px1, double & py1, double & pz1, double & px2, double & py2, double & pz2, int & iFbadevent)
Definition at line 241 of file gammaavm.cpp.
References eventChannel::_randy, getDaughterMass(), getTheta(), starlightConstants::pi, randomGenerator::Rndom(), and eventChannel::transform().
vmpt()
void Gammaavectormeson::vmpt (double W, double Y, double & E, double & px, double & py, double & pz, int & tcheck)
Definition at line 935 of file gammaavm.cpp.
References readLuminosity::_fptarray, eventChannel::_randy, _VMdpt, _VMNPT, _VMnumy, _VMptmax, _VMYmax, _VMYmin, starlightConstants::pi, and randomGenerator::Rndom().
Referenced by produceEvent().
Member Data Documentation
_angular_max
double Gammaavectormeson::_angular_max[100][200] private
Definition at line 124 of file gammaavm.h.
Referenced by Gammaavectormeson().
_baseFileName
const std::string readLuminosity::_baseFileName protected inherited
Definition at line 82 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and readLuminosity::read().
_bbs
beamBeamSystem eventChannel::_bbs inherited
Definition at line 73 of file eventchannel.h.
Referenced by starlightDpmJet::init(), starlightPythia::init(), momenta(), pickwy(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), starlightPythia::produceEvent(), starlightDpmJet::produceSingleEvent(), and pTgamma().
_beamLorentzGamma
double Gammaavectormeson::_beamLorentzGamma private
Definition at line 100 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_beamNucleus
int Gammaavectormeson::_beamNucleus private
Definition at line 119 of file gammaavm.h.
Referenced by e_produceEvent(), Gammaavectormeson(), and momenta().
_bslopeDef
int Gammaavectormeson::_bslopeDef private
Definition at line 116 of file gammaavm.h.
Referenced by Gammaavectormeson(), and momenta().
_bslopeVal
double Gammaavectormeson::_bslopeVal private
Definition at line 117 of file gammaavm.h.
Referenced by Gammaavectormeson(), and momenta().
_BWarray
double* readLuminosity::_BWarray inherited
Definition at line 52 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and pickwEgamq2().
_bwnormsave
double readLuminosity::_bwnormsave inherited
Definition at line 72 of file readinluminosity.h.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), readLuminosity::e_read(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaawidevm::Gammaawidevm(), and readLuminosity::read().
_cmsMaxPhotonEnergy
double Gammaavectormeson::_cmsMaxPhotonEnergy private
Definition at line 98 of file gammaavm.h.
Referenced by Gammaavectormeson().
_cmsMinPhotonEnergy
double Gammaavectormeson::_cmsMinPhotonEnergy private
Definition at line 99 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_dummy_pncs
photonNucleusCrossSection* Gammaavectormeson::_dummy_pncs private
Definition at line 123 of file gammaavm.h.
Referenced by Gammaavectormeson(), and ~Gammaavectormeson().
_eEnergy
double Gammaavectormeson::_eEnergy private
Definition at line 120 of file gammaavm.h.
Referenced by e_produceEvent(), Gammaavectormeson(), and pickwEgamq2().
_etaCutEnabled
bool eventChannel::_etaCutEnabled protected inherited
en/disables cut in eta
Definition at line 90 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_etaCutMax
double eventChannel::_etaCutMax protected inherited
maximum eta, if cut is enabled
Definition at line 92 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_etaCutMin
double eventChannel::_etaCutMin protected inherited
minimum eta, if cut is enabled
Definition at line 91 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_f_max
double readLuminosity::_f_max inherited
Definition at line 62 of file readinluminosity.h.
Referenced by readLuminosity::read(), Gammagammasingle::singleCrossSection(), and Gammagammaleptonpair::twoLeptonCrossSection().
_f_max1
double readLuminosity::_f_max1 inherited
Definition at line 63 of file readinluminosity.h.
Referenced by readLuminosity::read().
_f_max2
double readLuminosity::_f_max2 inherited
Definition at line 64 of file readinluminosity.h.
Referenced by readLuminosity::read().
_f_WYarray
double** readLuminosity::_f_WYarray inherited
Definition at line 58 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), pickwEgamq2(), and readLuminosity::~readLuminosity().
_f_WYmax
double readLuminosity::_f_WYmax inherited
Definition at line 66 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_Farray
double** readLuminosity::_Farray inherited
Definition at line 54 of file readinluminosity.h.
Referenced by pickwy(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), Gammagammaleptonpair::twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
_Farray1
double** readLuminosity::_Farray1 inherited
Definition at line 55 of file readinluminosity.h.
Referenced by pickwy(), readLuminosity::read(), and readLuminosity::~readLuminosity().
_Farray2
double** readLuminosity::_Farray2 inherited
Definition at line 56 of file readinluminosity.h.
Referenced by readLuminosity::read(), and readLuminosity::~readLuminosity().
_fptarray
double readLuminosity::_fptarray[500][500] inherited
Definition at line 70 of file readinluminosity.h.
Referenced by readLuminosity::read(), and vmpt().
_g_Earray
double** readLuminosity::_g_Earray inherited
Definition at line 59 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), and readLuminosity::~readLuminosity().
_g_Emax
double readLuminosity::_g_Emax inherited
Definition at line 67 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_g_EQ2array
std::vector< std::pair<double,std::vector<double> > >* readLuminosity::_g_EQ2array inherited
Definition at line 60 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), pickwEgamq2(), and readLuminosity::~readLuminosity().
_g_EQ2max
double readLuminosity::_g_EQ2max inherited
Definition at line 68 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_mass
double Gammaavectormeson::_mass private
Definition at line 112 of file gammaavm.h.
Referenced by getMass().
_nmbAccepted
unsigned long eventChannel::_nmbAccepted protected inherited
number of accepted events
Definition at line 85 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::nmbAccepted(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_nmbAttempts
unsigned long eventChannel::_nmbAttempts protected inherited
number of attempted events
Definition at line 84 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::nmbAttempts(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_pEnergy
double Gammaavectormeson::_pEnergy private
Definition at line 118 of file gammaavm.h.
Referenced by e_produceEvent(), Gammaavectormeson(), and momenta().
_phaseSpaceGen
nBodyPhaseSpaceGen* Gammaavectormeson::_phaseSpaceGen private
Definition at line 121 of file gammaavm.h.
Referenced by Gammaavectormeson(), and ~Gammaavectormeson().
_ProductionMode
int Gammaavectormeson::_ProductionMode private
Definition at line 95 of file gammaavm.h.
Referenced by Gammaavectormeson(), momenta(), pickwy(), and pTgamma().
_ptCutEnabled
bool eventChannel::_ptCutEnabled protected inherited
en/disables cut in pt
Definition at line 87 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_ptCutMax
double eventChannel::_ptCutMax protected inherited
maximum pt, if cut is enabled
Definition at line 89 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_ptCutMin
double eventChannel::_ptCutMin protected inherited
minimum pt, if cut is enabled
Definition at line 88 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammagammaleptonpair::produceEvent(), and produceEvent().
_randy
randomGenerator eventChannel::_randy inherited
Definition at line 74 of file eventchannel.h.
Referenced by e_produceEvent(), eventChannel::eventChannel(), Gammaavectormeson(), Gammagammaleptonpair::Gammagammaleptonpair(), getTheta(), starlightDpmJet::init(), starlightPythia::init(), momenta(), Gammagammaleptonpair::pairMomentum(), Gammagammasingle::parentMomentum(), Gammagammasingle::pickw(), Gammagammaleptonpair::pickw(), pickwEgamq2(), pickwy(), Gammagammasingle::picky(), Gammagammaleptonpair::picky(), Gammagammasingle::pp1(), Gammagammasingle::pp2(), Gammagammaleptonpair::pp_1(), Gammagammaleptonpair::pp_2(), starlightDpmJet::produceDoubleEvent(), Gammagammaleptonpair::produceEvent(), produceEvent(), Gammagammasingle::produceEvent(), pTgamma(), Gammagammaleptonpair::tauDecay(), twoBodyDecay(), Gammagammasingle::twoBodyDecay(), Gammagammaleptonpair::twoBodyDecay(), and vmpt().
_ReadInputgg_or_gP
const int readLuminosity::_ReadInputgg_or_gP protected inherited
Definition at line 80 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputinterferencemode
const int readLuminosity::_ReadInputinterferencemode protected inherited
Definition at line 81 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputNPT
const int readLuminosity::_ReadInputNPT protected inherited
Definition at line 75 of file readinluminosity.h.
Referenced by readLuminosity::read().
_ReadInputnumega
const int readLuminosity::_ReadInputnumega protected inherited
Definition at line 78 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_ReadInputnumQ2
const int readLuminosity::_ReadInputnumQ2 protected inherited
Definition at line 79 of file readinluminosity.h.
Referenced by readLuminosity::e_read().
_ReadInputnumw
const int readLuminosity::_ReadInputnumw protected inherited
Definition at line 77 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), readLuminosity::read(), and Gammagammaleptonpair::twoLeptonCrossSection().
_ReadInputnumy
const int readLuminosity::_ReadInputnumy protected inherited
Definition at line 76 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), readLuminosity::read(), and Gammagammaleptonpair::twoLeptonCrossSection().
_TargetBeam
int Gammaavectormeson::_TargetBeam private
Definition at line 102 of file gammaavm.h.
Referenced by momenta(), pickwy(), and pTgamma().
_targetMaxPhotonEnergy
double Gammaavectormeson::_targetMaxPhotonEnergy private
Definition at line 96 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_targetMinPhotonEnergy
double Gammaavectormeson::_targetMinPhotonEnergy private
Definition at line 97 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_targetRadius
double Gammaavectormeson::_targetRadius private
Definition at line 101 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_totalChannelCrossSection
double eventChannel::_totalChannelCrossSection protected inherited
Definition at line 94 of file eventchannel.h.
Referenced by eventChannel::getTotalChannelCrossSection(), and eventChannel::setTotalChannelCrossSection().
_VMbslope
double Gammaavectormeson::_VMbslope
Definition at line 83 of file gammaavm.h.
Referenced by e_Gammaanarrowvm::e_Gammaanarrowvm(), e_Gammaawidevm::e_Gammaawidevm(), Gammaaincoherentvm::Gammaaincoherentvm(), Gammaanarrowvm::Gammaanarrowvm(), Gammaavectormeson(), Gammaawidevm::Gammaawidevm(), and momenta().
_VMdpt
double Gammaavectormeson::_VMdpt private
Definition at line 115 of file gammaavm.h.
Referenced by Gammaavectormeson(), and vmpt().
_VMgamma_em
double Gammaavectormeson::_VMgamma_em private
Definition at line 106 of file gammaavm.h.
Referenced by Gammaavectormeson(), momenta(), and pTgamma().
_VMinterferencemode
int Gammaavectormeson::_VMinterferencemode private
Definition at line 94 of file gammaavm.h.
Referenced by Gammaavectormeson(), and produceEvent().
_VMNPT
double Gammaavectormeson::_VMNPT private
Definition at line 107 of file gammaavm.h.
Referenced by Gammaavectormeson(), and vmpt().
_VMnumega
int Gammaavectormeson::_VMnumega private
Definition at line 92 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_VMnumQ2
int Gammaavectormeson::_VMnumQ2 private
Definition at line 93 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwEgamq2().
_VMnumw
int Gammaavectormeson::_VMnumw private
Definition at line 90 of file gammaavm.h.
Referenced by Gammaavectormeson(), pickwEgamq2(), and pickwy().
_VMnumy
int Gammaavectormeson::_VMnumy private
Definition at line 91 of file gammaavm.h.
Referenced by pickwy(), and vmpt().
_VMpidtest
starlightConstants::particleTypeEnum Gammaavectormeson::_VMpidtest private
Definition at line 89 of file gammaavm.h.
Referenced by Gammaavectormeson(), getDaughterMass(), momenta(), and produceEvent().
_VMptmax
double Gammaavectormeson::_VMptmax private
Definition at line 114 of file gammaavm.h.
Referenced by Gammaavectormeson(), and vmpt().
_VMWmax
double Gammaavectormeson::_VMWmax private
Definition at line 108 of file gammaavm.h.
Referenced by Gammaavectormeson(), pickwEgamq2(), and pickwy().
_VMWmin
double Gammaavectormeson::_VMWmin private
Definition at line 109 of file gammaavm.h.
Referenced by Gammaavectormeson(), pickwEgamq2(), and pickwy().
_VMYmax
double Gammaavectormeson::_VMYmax private
Definition at line 110 of file gammaavm.h.
Referenced by pickwy(), and vmpt().
_VMYmin
double Gammaavectormeson::_VMYmin private
Definition at line 111 of file gammaavm.h.
Referenced by pickwy(), and vmpt().
_Warray
double* readLuminosity::_Warray inherited
Definition at line 51 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammagammasingle::pickw(), Gammagammaleptonpair::pickw(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), Gammagammaleptonpair::twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
_width
double Gammaavectormeson::_width private
Definition at line 113 of file gammaavm.h.
Referenced by getWidth().
_Yarray
double* readLuminosity::_Yarray inherited
Definition at line 53 of file readinluminosity.h.
Referenced by readLuminosity::e_read(), Gammagammasingle::pickw(), Gammagammasingle::picky(), Gammagammaleptonpair::picky(), readLuminosity::read(), Gammagammasingle::singleCrossSection(), Gammagammaleptonpair::twoLeptonCrossSection(), and readLuminosity::~readLuminosity().
N0
int Gammaavectormeson::N0 private
Definition at line 103 of file gammaavm.h.
Referenced by Gammaavectormeson(), momenta(), pickwEgamq2(), and pickwy().
N1
int Gammaavectormeson::N1 private
Definition at line 104 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwy().
N2
int Gammaavectormeson::N2 private
Definition at line 105 of file gammaavm.h.
Referenced by Gammaavectormeson(), and pickwy().
The documentation for this class was generated from the following files:
gammaavm.h
gammaavm.cpp