eSTARlight: main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <cstdlib>
#include "reportingUtils.h"
#include "starlight.h"
#include "eventfilewriter.h"
#include "starlightStandalone.h"
Functions
int main (int, const char **)
Function Documentation
main()
int main (int , const char **)
Definition at line 44 of file main.cpp.
References starlightStandalone::init(), printCompilerInfo(), printSvnVersion(), and starlightStandalone::run().